//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsB836201C962661A96064154C6843FCCBA5397082ED0381E9B1056799C41C645A))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsB836201C962661A96064154C6843FCCBA5397082ED0381E9B1056799C41C645A : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySetsB836201C962661A96064154C6843FCCBA5397082ED0381E9B1056799C41C645A()
        {
            this.EdmEntityContainerName = "TrainingEntities";
            this.StoreEntityContainerName = "TrainingModelStoreContainer";
            this.HashOverMappingClosure = "fbed3132bbd941a55dbd8dda061346eed12637254db765d69f26baba87c66606";
            this.HashOverAllExtentViews = "d49171952624dcd59e05cc20445729044931d65e652b9af9961c5948db4f9a71";
            this.ViewCount = 26;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.CUST
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.CUST", @"
    SELECT VALUE -- Constructing CUST
        [TrainingModel.Store.CUST](T1.[CUST.CUST_ID], T1.[CUST.CUST_NO], T1.[CUST.CUST_TYPE], T1.[CUST.CUST_NAME], T1.[CUST.IDENTITY_TYPE], T1.[CUST.IDENTITY_NO], T1.[CUST.USR_CRT], T1.[CUST.DTM_CRT], T1.[CUST.USR_UPD], T1.[CUST.DTM_UPD], T1.[CUST.BIRTH_DT], T1.[CUST.BIRTH_PLACE], T1.[CUST.MARITAL_STATUS], T1.CUST_RELIGION, T1.CUST_NATIONALITY, T1.[CUST.MONTHLY_INCOME])
    FROM (
        SELECT 
            T.CustId AS [CUST.CUST_ID], 
            T.CustNo AS [CUST.CUST_NO], 
            T.CustType AS [CUST.CUST_TYPE], 
            T.CustName AS [CUST.CUST_NAME], 
            T.IdentityType AS [CUST.IDENTITY_TYPE], 
            T.IdentityNo AS [CUST.IDENTITY_NO], 
            T.LastUserTimestamp.UsrCrt AS [CUST.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [CUST.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [CUST.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [CUST.DTM_UPD], 
            T.BirthDt AS [CUST.BIRTH_DT], 
            T.BirthPlace AS [CUST.BIRTH_PLACE], 
            T.MaritalStatus AS [CUST.MARITAL_STATUS], 
            T.Religion AS CUST_RELIGION, 
            T.Nationality AS CUST_NATIONALITY, 
            T.MonthlyIncome AS [CUST.MONTHLY_INCOME], 
            True AS _from0
        FROM TrainingEntities.Custs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.CUST_ADDR
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.CUST_ADDR", @"
    SELECT VALUE -- Constructing CUST_ADDR
        [TrainingModel.Store.CUST_ADDR](T1.[CUST_ADDR.CUST_ADDR_ID], T1.[CUST_ADDR.CUST_ID], T1.[CUST_ADDR.ADDRESS], T1.[CUST_ADDR.ADDRESS_TYPE], T1.[CUST_ADDR.RT], T1.[CUST_ADDR.RW], T1.[CUST_ADDR.KELURAHAN], T1.[CUST_ADDR.KECAMATAN], T1.[CUST_ADDR.CITY], T1.[CUST_ADDR.ZIPCODE], T1.[CUST_ADDR.USR_CRT], T1.[CUST_ADDR.DTM_CRT], T1.[CUST_ADDR.USR_UPD], T1.[CUST_ADDR.DTM_UPD])
    FROM (
        SELECT 
            T.CustAddrId AS [CUST_ADDR.CUST_ADDR_ID], 
            T.CustId AS [CUST_ADDR.CUST_ID], 
            T.Address AS [CUST_ADDR.ADDRESS], 
            T.AddressType AS [CUST_ADDR.ADDRESS_TYPE], 
            T.Rt AS [CUST_ADDR.RT], 
            T.Rw AS [CUST_ADDR.RW], 
            T.Kelurahan AS [CUST_ADDR.KELURAHAN], 
            T.Kecamatan AS [CUST_ADDR.KECAMATAN], 
            T.City AS [CUST_ADDR.CITY], 
            T.Zipcode AS [CUST_ADDR.ZIPCODE], 
            T.LastUserTimestamp.UsrCrt AS [CUST_ADDR.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [CUST_ADDR.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [CUST_ADDR.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [CUST_ADDR.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.CustAddrs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PROD_TRX_D
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PROD_TRX_D", @"
    SELECT VALUE -- Constructing PROD_TRX_D
        [TrainingModel.Store.PROD_TRX_D](T1.[PROD_TRX_D.PROD_TRX_D_ID], T1.[PROD_TRX_D.PROD_TRX_H_ID], T1.[PROD_TRX_D.PRODUCT_D_ID], T1.[PROD_TRX_D.QTY], T1.[PROD_TRX_D.USR_CRT], T1.[PROD_TRX_D.DTM_CRT], T1.[PROD_TRX_D.USR_UPD], T1.[PROD_TRX_D.DTM_UPD])
    FROM (
        SELECT 
            T.ProdTrxDId AS [PROD_TRX_D.PROD_TRX_D_ID], 
            T.ProdTrxHId AS [PROD_TRX_D.PROD_TRX_H_ID], 
            T.ProductDId AS [PROD_TRX_D.PRODUCT_D_ID], 
            T.Qty AS [PROD_TRX_D.QTY], 
            T.LastUserTimestamp.UsrCrt AS [PROD_TRX_D.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PROD_TRX_D.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PROD_TRX_D.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PROD_TRX_D.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.ProdTrxDs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PROD_TRX_H
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PROD_TRX_H", @"
    SELECT VALUE -- Constructing PROD_TRX_H
        [TrainingModel.Store.PROD_TRX_H](T1.[PROD_TRX_H.PROD_TRX_H_ID], T1.[PROD_TRX_H.PROD_TRX_NO], T1.[PROD_TRX_H.PROD_TRX_DT], T1.[PROD_TRX_H.CUST_ID], T1.[PROD_TRX_H.TOTAL_PRICE], T1.[PROD_TRX_H.USR_CRT], T1.[PROD_TRX_H.DTM_CRT], T1.[PROD_TRX_H.USR_UPD], T1.[PROD_TRX_H.DTM_UPD])
    FROM (
        SELECT 
            T.ProdTrxHId AS [PROD_TRX_H.PROD_TRX_H_ID], 
            T.ProdTrxNo AS [PROD_TRX_H.PROD_TRX_NO], 
            T.ProdTrxDt AS [PROD_TRX_H.PROD_TRX_DT], 
            T.CustId AS [PROD_TRX_H.CUST_ID], 
            T.TotalPrice AS [PROD_TRX_H.TOTAL_PRICE], 
            T.LastUserTimestamp.UsrCrt AS [PROD_TRX_H.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PROD_TRX_H.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PROD_TRX_H.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PROD_TRX_H.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.ProdTrxHs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Custs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Custs", "\r\n    SELECT VALUE -- Constructing Custs\r\n        [TrainingModel.Cust](T2.Cust_Cu" +
                    "stId, T2.Cust_CustNo, T2.Cust_CustType, T2.Cust_CustName, T2.Cust_IdentityType, " +
                    "T2.Cust_IdentityNo, T2.Cust_BirthDt, T2.Cust_BirthPlace, T2.Cust_MaritalStatus, " +
                    "T2.Cust_Religion, T2.Cust_Nationality, T2.Cust_MonthlyIncome, T2.Cust_LastUserTi" +
                    "mestamp)\r\n    FROM (\r\n        SELECT -- Constructing LastUserTimestamp\r\n        " +
                    "    T1.Cust_CustId, \r\n            T1.Cust_CustNo, \r\n            T1.Cust_CustType" +
                    ", \r\n            T1.Cust_CustName, \r\n            T1.Cust_IdentityType, \r\n        " +
                    "    T1.Cust_IdentityNo, \r\n            T1.Cust_BirthDt, \r\n            T1.Cust_Bir" +
                    "thPlace, \r\n            T1.Cust_MaritalStatus, \r\n            T1.Cust_Religion, \r\n" +
                    "            T1.Cust_Nationality, \r\n            T1.Cust_MonthlyIncome, \r\n        " +
                    "    [TrainingModel.UserTimestamp](T1.Cust_LastUserTimestamp_UsrCrt, T1.Cust_Last" +
                    "UserTimestamp_DtmCrt, T1.Cust_LastUserTimestamp_UsrUpd, T1.Cust_LastUserTimestam" +
                    "p_DtmUpd) AS Cust_LastUserTimestamp\r\n        FROM (\r\n            SELECT \r\n      " +
                    "          T.CUST_ID AS Cust_CustId, \r\n                T.CUST_NO AS Cust_CustNo, " +
                    "\r\n                T.CUST_TYPE AS Cust_CustType, \r\n                T.CUST_NAME AS" +
                    " Cust_CustName, \r\n                T.IDENTITY_TYPE AS Cust_IdentityType, \r\n      " +
                    "          T.IDENTITY_NO AS Cust_IdentityNo, \r\n                T.BIRTH_DT AS Cust" +
                    "_BirthDt, \r\n                T.BIRTH_PLACE AS Cust_BirthPlace, \r\n                " +
                    "T.MARITAL_STATUS AS Cust_MaritalStatus, \r\n                T.RELIGION AS Cust_Rel" +
                    "igion, \r\n                T.NATIONALITY AS Cust_Nationality, \r\n                T." +
                    "MONTHLY_INCOME AS Cust_MonthlyIncome, \r\n                T.USR_CRT AS Cust_LastUs" +
                    "erTimestamp_UsrCrt, \r\n                T.DTM_CRT AS Cust_LastUserTimestamp_DtmCrt" +
                    ", \r\n                T.USR_UPD AS Cust_LastUserTimestamp_UsrUpd, \r\n              " +
                    "  T.DTM_UPD AS Cust_LastUserTimestamp_DtmUpd, \r\n                True AS _from0\r\n" +
                    "            FROM TrainingModelStoreContainer.CUST AS T\r\n        ) AS T1\r\n    ) A" +
                    "S T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.CustAddrs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.CustAddrs", "\r\n    SELECT VALUE -- Constructing CustAddrs\r\n        [TrainingModel.CustAddr](T2" +
                    ".CustAddr_CustAddrId, T2.CustAddr_CustId, T2.CustAddr_Address, T2.CustAddr_Addre" +
                    "ssType, T2.CustAddr_Rt, T2.CustAddr_Rw, T2.CustAddr_Kelurahan, T2.CustAddr_Kecam" +
                    "atan, T2.CustAddr_City, T2.CustAddr_Zipcode, T2.CustAddr_LastUserTimestamp)\r\n   " +
                    " FROM (\r\n        SELECT -- Constructing LastUserTimestamp\r\n            T1.CustAd" +
                    "dr_CustAddrId, \r\n            T1.CustAddr_CustId, \r\n            T1.CustAddr_Addre" +
                    "ss, \r\n            T1.CustAddr_AddressType, \r\n            T1.CustAddr_Rt, \r\n     " +
                    "       T1.CustAddr_Rw, \r\n            T1.CustAddr_Kelurahan, \r\n            T1.Cus" +
                    "tAddr_Kecamatan, \r\n            T1.CustAddr_City, \r\n            T1.CustAddr_Zipco" +
                    "de, \r\n            [TrainingModel.UserTimestamp](T1.CustAddr_LastUserTimestamp_Us" +
                    "rCrt, T1.CustAddr_LastUserTimestamp_DtmCrt, T1.CustAddr_LastUserTimestamp_UsrUpd" +
                    ", T1.CustAddr_LastUserTimestamp_DtmUpd) AS CustAddr_LastUserTimestamp\r\n        F" +
                    "ROM (\r\n            SELECT \r\n                T.CUST_ADDR_ID AS CustAddr_CustAddrI" +
                    "d, \r\n                T.CUST_ID AS CustAddr_CustId, \r\n                T.ADDRESS A" +
                    "S CustAddr_Address, \r\n                T.ADDRESS_TYPE AS CustAddr_AddressType, \r\n" +
                    "                T.RT AS CustAddr_Rt, \r\n                T.RW AS CustAddr_Rw, \r\n  " +
                    "              T.KELURAHAN AS CustAddr_Kelurahan, \r\n                T.KECAMATAN A" +
                    "S CustAddr_Kecamatan, \r\n                T.CITY AS CustAddr_City, \r\n             " +
                    "   T.ZIPCODE AS CustAddr_Zipcode, \r\n                T.USR_CRT AS CustAddr_LastUs" +
                    "erTimestamp_UsrCrt, \r\n                T.DTM_CRT AS CustAddr_LastUserTimestamp_Dt" +
                    "mCrt, \r\n                T.USR_UPD AS CustAddr_LastUserTimestamp_UsrUpd, \r\n      " +
                    "          T.DTM_UPD AS CustAddr_LastUserTimestamp_DtmUpd, \r\n                True" +
                    " AS _from0\r\n            FROM TrainingModelStoreContainer.CUST_ADDR AS T\r\n       " +
                    " ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProdTrxDs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProdTrxDs", @"
    SELECT VALUE -- Constructing ProdTrxDs
        [TrainingModel.ProdTrxD](T2.ProdTrxD_ProdTrxDId, T2.ProdTrxD_ProdTrxHId, T2.ProdTrxD_ProductDId, T2.ProdTrxD_Qty, T2.ProdTrxD_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProdTrxD_ProdTrxDId, 
            T1.ProdTrxD_ProdTrxHId, 
            T1.ProdTrxD_ProductDId, 
            T1.ProdTrxD_Qty, 
            [TrainingModel.UserTimestamp](T1.ProdTrxD_LastUserTimestamp_UsrCrt, T1.ProdTrxD_LastUserTimestamp_DtmCrt, T1.ProdTrxD_LastUserTimestamp_UsrUpd, T1.ProdTrxD_LastUserTimestamp_DtmUpd) AS ProdTrxD_LastUserTimestamp
        FROM (
            SELECT 
                T.PROD_TRX_D_ID AS ProdTrxD_ProdTrxDId, 
                T.PROD_TRX_H_ID AS ProdTrxD_ProdTrxHId, 
                T.PRODUCT_D_ID AS ProdTrxD_ProductDId, 
                T.QTY AS ProdTrxD_Qty, 
                T.USR_CRT AS ProdTrxD_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProdTrxD_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProdTrxD_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProdTrxD_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PROD_TRX_D AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProdTrxHs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProdTrxHs", @"
    SELECT VALUE -- Constructing ProdTrxHs
        [TrainingModel.ProdTrxH](T2.ProdTrxH_ProdTrxHId, T2.ProdTrxH_ProdTrxNo, T2.ProdTrxH_ProdTrxDt, T2.ProdTrxH_CustId, T2.ProdTrxH_TotalPrice, T2.ProdTrxH_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProdTrxH_ProdTrxHId, 
            T1.ProdTrxH_ProdTrxNo, 
            T1.ProdTrxH_ProdTrxDt, 
            T1.ProdTrxH_CustId, 
            T1.ProdTrxH_TotalPrice, 
            [TrainingModel.UserTimestamp](T1.ProdTrxH_LastUserTimestamp_UsrCrt, T1.ProdTrxH_LastUserTimestamp_DtmCrt, T1.ProdTrxH_LastUserTimestamp_UsrUpd, T1.ProdTrxH_LastUserTimestamp_DtmUpd) AS ProdTrxH_LastUserTimestamp
        FROM (
            SELECT 
                T.PROD_TRX_H_ID AS ProdTrxH_ProdTrxHId, 
                T.PROD_TRX_NO AS ProdTrxH_ProdTrxNo, 
                T.PROD_TRX_DT AS ProdTrxH_ProdTrxDt, 
                T.CUST_ID AS ProdTrxH_CustId, 
                T.TOTAL_PRICE AS ProdTrxH_TotalPrice, 
                T.USR_CRT AS ProdTrxH_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProdTrxH_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProdTrxH_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProdTrxH_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PROD_TRX_H AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_MASTER
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_MASTER", @"
    SELECT VALUE -- Constructing REF_MASTER
        [TrainingModel.Store.REF_MASTER](T1.[REF_MASTER.REF_MASTER_ID], T1.[REF_MASTER.MASTER_CODE], T1.[REF_MASTER.DESCRIPTION], T1.[REF_MASTER.MASTER_TYPE], T1.[REF_MASTER.USR_CRT], T1.[REF_MASTER.DTM_CRT], T1.[REF_MASTER.USR_UPD], T1.[REF_MASTER.DTM_UPD])
    FROM (
        SELECT 
            T.RefMasterId AS [REF_MASTER.REF_MASTER_ID], 
            T.MasterCode AS [REF_MASTER.MASTER_CODE], 
            T.Description AS [REF_MASTER.DESCRIPTION], 
            T.MasterType AS [REF_MASTER.MASTER_TYPE], 
            T.LastUserTimestamp.UsrCrt AS [REF_MASTER.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [REF_MASTER.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [REF_MASTER.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [REF_MASTER.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.RefMasters AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefMasters
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefMasters", @"
    SELECT VALUE -- Constructing RefMasters
        [TrainingModel.RefMaster](T2.RefMaster_RefMasterId, T2.RefMaster_MasterCode, T2.RefMaster_Description, T2.RefMaster_MasterType, T2.RefMaster_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefMaster_RefMasterId, 
            T1.RefMaster_MasterCode, 
            T1.RefMaster_Description, 
            T1.RefMaster_MasterType, 
            [TrainingModel.UserTimestamp](T1.RefMaster_LastUserTimestamp_UsrCrt, T1.RefMaster_LastUserTimestamp_DtmCrt, T1.RefMaster_LastUserTimestamp_UsrUpd, T1.RefMaster_LastUserTimestamp_DtmUpd) AS RefMaster_LastUserTimestamp
        FROM (
            SELECT 
                T.REF_MASTER_ID AS RefMaster_RefMasterId, 
                T.MASTER_CODE AS RefMaster_MasterCode, 
                T.DESCRIPTION AS RefMaster_Description, 
                T.MASTER_TYPE AS RefMaster_MasterType, 
                T.USR_CRT AS RefMaster_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS RefMaster_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS RefMaster_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS RefMaster_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.REF_MASTER AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.CUSTOMER_HANDLING
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.CUSTOMER_HANDLING", "\r\n    SELECT VALUE -- Constructing CUSTOMER_HANDLING\r\n        [TrainingModel.Stor" +
                    "e.CUSTOMER_HANDLING](T1.[CUSTOMER_HANDLING.CUSTOMER_HANDLING_ID], T1.[CUSTOMER_H" +
                    "ANDLING.REGISTRATION_NO], T1.[CUSTOMER_HANDLING.CUSTOMER_NAME], T1.[CUSTOMER_HAN" +
                    "DLING.MOBILE_PHONE_NO], T1.[CUSTOMER_HANDLING.EMAIL], T1.[CUSTOMER_HANDLING.SERV" +
                    "ICE_CATEGORY], T1.[CUSTOMER_HANDLING.MEDIA_OF_SERVICE], T1.[CUSTOMER_HANDLING.CH" +
                    "RONOLOGIC], T1.[CUSTOMER_HANDLING.SERVICE_STATUS], T1.[CUSTOMER_HANDLING.ADMIN_F" +
                    "EE], T1.[CUSTOMER_HANDLING.COMPLETION_DT], T1.[CUSTOMER_HANDLING.USR_CRT], T1.[C" +
                    "USTOMER_HANDLING.DTM_CRT], T1.[CUSTOMER_HANDLING.USR_UPD], T1.[CUSTOMER_HANDLING" +
                    ".DTM_UPD])\r\n    FROM (\r\n        SELECT \r\n            T.CustomerHandlingId AS [CU" +
                    "STOMER_HANDLING.CUSTOMER_HANDLING_ID], \r\n            T.RegistrationNo AS [CUSTOM" +
                    "ER_HANDLING.REGISTRATION_NO], \r\n            T.CustomerName AS [CUSTOMER_HANDLING" +
                    ".CUSTOMER_NAME], \r\n            T.MobilePhoneNo AS [CUSTOMER_HANDLING.MOBILE_PHON" +
                    "E_NO], \r\n            T.Email AS [CUSTOMER_HANDLING.EMAIL], \r\n            T.Servi" +
                    "ceCategory AS [CUSTOMER_HANDLING.SERVICE_CATEGORY], \r\n            T.MediaOfServi" +
                    "ce AS [CUSTOMER_HANDLING.MEDIA_OF_SERVICE], \r\n            T.Chronologic AS [CUST" +
                    "OMER_HANDLING.CHRONOLOGIC], \r\n            T.ServiceStatus AS [CUSTOMER_HANDLING." +
                    "SERVICE_STATUS], \r\n            T.AdminFee AS [CUSTOMER_HANDLING.ADMIN_FEE], \r\n  " +
                    "          T.CompletionDt AS [CUSTOMER_HANDLING.COMPLETION_DT], \r\n            T.L" +
                    "astUserTimestamp.UsrCrt AS [CUSTOMER_HANDLING.USR_CRT], \r\n            T.LastUser" +
                    "Timestamp.DtmCrt AS [CUSTOMER_HANDLING.DTM_CRT], \r\n            T.LastUserTimesta" +
                    "mp.UsrUpd AS [CUSTOMER_HANDLING.USR_UPD], \r\n            T.LastUserTimestamp.DtmU" +
                    "pd AS [CUSTOMER_HANDLING.DTM_UPD], \r\n            True AS _from0\r\n        FROM Tr" +
                    "ainingEntities.CustomerHandlings AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.CustomerHandlings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2587);
            viewString.Append("\r\n    SELECT VALUE -- Constructing CustomerHandlings\r\n        [TrainingModel.Cus");
            viewString.Append("tomerHandling](T2.CustomerHandling_CustomerHandlingId, T2.CustomerHandling_Regis");
            viewString.Append("trationNo, T2.CustomerHandling_CustomerName, T2.CustomerHandling_MobilePhoneNo, ");
            viewString.Append("T2.CustomerHandling_Email, T2.CustomerHandling_ServiceCategory, T2.CustomerHandl");
            viewString.Append("ing_MediaOfService, T2.CustomerHandling_Chronologic, T2.CustomerHandling_Service");
            viewString.Append("Status, T2.CustomerHandling_AdminFee, T2.CustomerHandling_CompletionDt, T2.Custo");
            viewString.Append("merHandling_LastUserTimestamp)\r\n    FROM (\r\n        SELECT -- Constructing LastU");
            viewString.Append("serTimestamp\r\n            T1.CustomerHandling_CustomerHandlingId, \r\n            ");
            viewString.Append("T1.CustomerHandling_RegistrationNo, \r\n            T1.CustomerHandling_CustomerNa");
            viewString.Append("me, \r\n            T1.CustomerHandling_MobilePhoneNo, \r\n            T1.CustomerHa");
            viewString.Append("ndling_Email, \r\n            T1.CustomerHandling_ServiceCategory, \r\n            T");
            viewString.Append("1.CustomerHandling_MediaOfService, \r\n            T1.CustomerHandling_Chronologic");
            viewString.Append(", \r\n            T1.CustomerHandling_ServiceStatus, \r\n            T1.CustomerHand");
            viewString.Append("ling_AdminFee, \r\n            T1.CustomerHandling_CompletionDt, \r\n            [Tr");
            viewString.Append("ainingModel.UserTimestamp](T1.CustomerHandling_LastUserTimestamp_UsrCrt, T1.Cust");
            viewString.Append("omerHandling_LastUserTimestamp_DtmCrt, T1.CustomerHandling_LastUserTimestamp_Usr");
            viewString.Append("Upd, T1.CustomerHandling_LastUserTimestamp_DtmUpd) AS CustomerHandling_LastUserT");
            viewString.Append("imestamp\r\n        FROM (\r\n            SELECT \r\n                T.CUSTOMER_HANDLI");
            viewString.Append("NG_ID AS CustomerHandling_CustomerHandlingId, \r\n                T.REGISTRATION_N");
            viewString.Append("O AS CustomerHandling_RegistrationNo, \r\n                T.CUSTOMER_NAME AS Custo");
            viewString.Append("merHandling_CustomerName, \r\n                T.MOBILE_PHONE_NO AS CustomerHandlin");
            viewString.Append("g_MobilePhoneNo, \r\n                T.EMAIL AS CustomerHandling_Email, \r\n        ");
            viewString.Append("        T.SERVICE_CATEGORY AS CustomerHandling_ServiceCategory, \r\n              ");
            viewString.Append("  T.MEDIA_OF_SERVICE AS CustomerHandling_MediaOfService, \r\n                T.CHR");
            viewString.Append("ONOLOGIC AS CustomerHandling_Chronologic, \r\n                T.SERVICE_STATUS AS ");
            viewString.Append("CustomerHandling_ServiceStatus, \r\n                T.ADMIN_FEE AS CustomerHandlin");
            viewString.Append("g_AdminFee, \r\n                T.COMPLETION_DT AS CustomerHandling_CompletionDt, ");
            viewString.Append("\r\n                T.USR_CRT AS CustomerHandling_LastUserTimestamp_UsrCrt, \r\n    ");
            viewString.Append("            T.DTM_CRT AS CustomerHandling_LastUserTimestamp_DtmCrt, \r\n          ");
            viewString.Append("      T.USR_UPD AS CustomerHandling_LastUserTimestamp_UsrUpd, \r\n                ");
            viewString.Append("T.DTM_UPD AS CustomerHandling_LastUserTimestamp_DtmUpd, \r\n                True A");
            viewString.Append("S _from0\r\n            FROM TrainingModelStoreContainer.CUSTOMER_HANDLING AS T\r\n ");
            viewString.Append("       ) AS T1\r\n    ) AS T2");
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.CustomerHandlings", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.SUPPL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.SUPPL", @"
    SELECT VALUE -- Constructing SUPPL
        [TrainingModel.Store.SUPPL](T1.[SUPPL.SUPPL_ID], T1.[SUPPL.SUPPL_NO], T1.[SUPPL.SUPPL_NAME], T1.[SUPPL.SUPPL_ADDRESS], T1.[SUPPL.SUPPL_RT], T1.[SUPPL.SUPPL_RW], T1.[SUPPL.SUPPL_KELURAHAN], T1.[SUPPL.SUPPL_KECAMATAN], T1.[SUPPL.SUPPL_CITY], T1.[SUPPL.SUPPL_ZIPCODE], T1.[SUPPL.USR_CRT], T1.[SUPPL.DTM_CRT], T1.[SUPPL.USR_UPD], T1.[SUPPL.DTM_UPD], T1.SUPPL_PRODUCE)
    FROM (
        SELECT 
            T.SupplId AS [SUPPL.SUPPL_ID], 
            T.SupplNo AS [SUPPL.SUPPL_NO], 
            T.SupplName AS [SUPPL.SUPPL_NAME], 
            T.SupplAddress AS [SUPPL.SUPPL_ADDRESS], 
            T.SupplRt AS [SUPPL.SUPPL_RT], 
            T.SupplRw AS [SUPPL.SUPPL_RW], 
            T.SupplKelurahan AS [SUPPL.SUPPL_KELURAHAN], 
            T.SupplKecamatan AS [SUPPL.SUPPL_KECAMATAN], 
            T.SupplCity AS [SUPPL.SUPPL_CITY], 
            T.SupplZipcode AS [SUPPL.SUPPL_ZIPCODE], 
            T.LastUserTimestamp.UsrCrt AS [SUPPL.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [SUPPL.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [SUPPL.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [SUPPL.DTM_UPD], 
            T.Produce AS SUPPL_PRODUCE, 
            True AS _from0
        FROM TrainingEntities.Suppls AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Suppls
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Suppls", "\r\n    SELECT VALUE -- Constructing Suppls\r\n        [TrainingModel.Suppl](T2.Suppl" +
                    "_SupplId, T2.Suppl_SupplNo, T2.Suppl_SupplName, T2.Suppl_SupplAddress, T2.Suppl_" +
                    "SupplRt, T2.Suppl_SupplRw, T2.Suppl_SupplKelurahan, T2.Suppl_SupplKecamatan, T2." +
                    "Suppl_SupplCity, T2.Suppl_SupplZipcode, T2.Suppl_Produce, T2.Suppl_LastUserTimes" +
                    "tamp)\r\n    FROM (\r\n        SELECT -- Constructing LastUserTimestamp\r\n           " +
                    " T1.Suppl_SupplId, \r\n            T1.Suppl_SupplNo, \r\n            T1.Suppl_SupplN" +
                    "ame, \r\n            T1.Suppl_SupplAddress, \r\n            T1.Suppl_SupplRt, \r\n    " +
                    "        T1.Suppl_SupplRw, \r\n            T1.Suppl_SupplKelurahan, \r\n            T" +
                    "1.Suppl_SupplKecamatan, \r\n            T1.Suppl_SupplCity, \r\n            T1.Suppl" +
                    "_SupplZipcode, \r\n            T1.Suppl_Produce, \r\n            [TrainingModel.User" +
                    "Timestamp](T1.Suppl_LastUserTimestamp_UsrCrt, T1.Suppl_LastUserTimestamp_DtmCrt," +
                    " T1.Suppl_LastUserTimestamp_UsrUpd, T1.Suppl_LastUserTimestamp_DtmUpd) AS Suppl_" +
                    "LastUserTimestamp\r\n        FROM (\r\n            SELECT \r\n                T.SUPPL_" +
                    "ID AS Suppl_SupplId, \r\n                T.SUPPL_NO AS Suppl_SupplNo, \r\n          " +
                    "      T.SUPPL_NAME AS Suppl_SupplName, \r\n                T.SUPPL_ADDRESS AS Supp" +
                    "l_SupplAddress, \r\n                T.SUPPL_RT AS Suppl_SupplRt, \r\n               " +
                    " T.SUPPL_RW AS Suppl_SupplRw, \r\n                T.SUPPL_KELURAHAN AS Suppl_Suppl" +
                    "Kelurahan, \r\n                T.SUPPL_KECAMATAN AS Suppl_SupplKecamatan, \r\n      " +
                    "          T.SUPPL_CITY AS Suppl_SupplCity, \r\n                T.SUPPL_ZIPCODE AS " +
                    "Suppl_SupplZipcode, \r\n                T.PRODUCE AS Suppl_Produce, \r\n            " +
                    "    T.USR_CRT AS Suppl_LastUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS " +
                    "Suppl_LastUserTimestamp_DtmCrt, \r\n                T.USR_UPD AS Suppl_LastUserTim" +
                    "estamp_UsrUpd, \r\n                T.DTM_UPD AS Suppl_LastUserTimestamp_DtmUpd, \r\n" +
                    "                True AS _from0\r\n            FROM TrainingModelStoreContainer.SUP" +
                    "PL AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PRODUCT_D
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PRODUCT_D", @"
    SELECT VALUE -- Constructing PRODUCT_D
        [TrainingModel.Store.PRODUCT_D](T1.[PRODUCT_D.PRODUCT_D_ID], T1.[PRODUCT_D.PRODUCT_H_ID], T1.[PRODUCT_D.MODEL_CODE], T1.[PRODUCT_D.MODEL_NAME], T1.[PRODUCT_D.PRICE], T1.[PRODUCT_D.USR_CRT], T1.[PRODUCT_D.DTM_CRT], T1.[PRODUCT_D.USR_UPD], T1.[PRODUCT_D.DTM_UPD], T1.[PRODUCT_D.RELEASE_DT])
    FROM (
        SELECT 
            T.ProductDId AS [PRODUCT_D.PRODUCT_D_ID], 
            T.ProductHId AS [PRODUCT_D.PRODUCT_H_ID], 
            T.ModelCode AS [PRODUCT_D.MODEL_CODE], 
            T.ModelName AS [PRODUCT_D.MODEL_NAME], 
            T.Price AS [PRODUCT_D.PRICE], 
            T.LastUserTimestamp.UsrCrt AS [PRODUCT_D.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PRODUCT_D.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PRODUCT_D.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PRODUCT_D.DTM_UPD], 
            T.ReleaseDt AS [PRODUCT_D.RELEASE_DT], 
            True AS _from0
        FROM TrainingEntities.ProductDs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProductDs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProductDs", @"
    SELECT VALUE -- Constructing ProductDs
        [TrainingModel.ProductD](T2.ProductD_ProductDId, T2.ProductD_ProductHId, T2.ProductD_ModelCode, T2.ProductD_ModelName, T2.ProductD_Price, T2.ProductD_ReleaseDt, T2.ProductD_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProductD_ProductDId, 
            T1.ProductD_ProductHId, 
            T1.ProductD_ModelCode, 
            T1.ProductD_ModelName, 
            T1.ProductD_Price, 
            T1.ProductD_ReleaseDt, 
            [TrainingModel.UserTimestamp](T1.ProductD_LastUserTimestamp_UsrCrt, T1.ProductD_LastUserTimestamp_DtmCrt, T1.ProductD_LastUserTimestamp_UsrUpd, T1.ProductD_LastUserTimestamp_DtmUpd) AS ProductD_LastUserTimestamp
        FROM (
            SELECT 
                T.PRODUCT_D_ID AS ProductD_ProductDId, 
                T.PRODUCT_H_ID AS ProductD_ProductHId, 
                T.MODEL_CODE AS ProductD_ModelCode, 
                T.MODEL_NAME AS ProductD_ModelName, 
                T.PRICE AS ProductD_Price, 
                T.RELEASE_DT AS ProductD_ReleaseDt, 
                T.USR_CRT AS ProductD_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProductD_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProductD_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProductD_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PRODUCT_D AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PRODUCT_H
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PRODUCT_H", @"
    SELECT VALUE -- Constructing PRODUCT_H
        [TrainingModel.Store.PRODUCT_H](T1.[PRODUCT_H.PRODUCT_H_ID], T1.[PRODUCT_H.BRAND_CODE], T1.[PRODUCT_H.BRAND_NAME], T1.[PRODUCT_H.USR_CRT], T1.[PRODUCT_H.DTM_CRT], T1.[PRODUCT_H.USR_UPD], T1.[PRODUCT_H.DTM_UPD])
    FROM (
        SELECT 
            T.ProductHId AS [PRODUCT_H.PRODUCT_H_ID], 
            T.BrandCode AS [PRODUCT_H.BRAND_CODE], 
            T.BrandName AS [PRODUCT_H.BRAND_NAME], 
            T.LastUserTimestamp.UsrCrt AS [PRODUCT_H.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PRODUCT_H.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PRODUCT_H.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PRODUCT_H.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.ProductHs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProductHs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProductHs", @"
    SELECT VALUE -- Constructing ProductHs
        [TrainingModel.ProductH](T2.ProductH_ProductHId, T2.ProductH_BrandCode, T2.ProductH_BrandName, T2.ProductH_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProductH_ProductHId, 
            T1.ProductH_BrandCode, 
            T1.ProductH_BrandName, 
            [TrainingModel.UserTimestamp](T1.ProductH_LastUserTimestamp_UsrCrt, T1.ProductH_LastUserTimestamp_DtmCrt, T1.ProductH_LastUserTimestamp_UsrUpd, T1.ProductH_LastUserTimestamp_DtmUpd) AS ProductH_LastUserTimestamp
        FROM (
            SELECT 
                T.PRODUCT_H_ID AS ProductH_ProductHId, 
                T.BRAND_CODE AS ProductH_BrandCode, 
                T.BRAND_NAME AS ProductH_BrandName, 
                T.USR_CRT AS ProductH_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProductH_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProductH_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProductH_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PRODUCT_H AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_COURSE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_COURSE", @"
    SELECT VALUE -- Constructing REF_COURSE
        [TrainingModel.Store.REF_COURSE](T1.[REF_COURSE.REF_COURSE_ID], T1.[REF_COURSE.COURSE_CODE], T1.[REF_COURSE.COURSE_NAME], T1.[REF_COURSE.DTM_CRT], T1.[REF_COURSE.USR_CRT], T1.[REF_COURSE.DTM_UPD], T1.[REF_COURSE.USR_UPD])
    FROM (
        SELECT 
            T.RefCourseId AS [REF_COURSE.REF_COURSE_ID], 
            T.CourseCode AS [REF_COURSE.COURSE_CODE], 
            T.CourseName AS [REF_COURSE.COURSE_NAME], 
            T.LastUserTimestamp.DtmCrt AS [REF_COURSE.DTM_CRT], 
            T.LastUserTimestamp.UsrCrt AS [REF_COURSE.USR_CRT], 
            T.LastUserTimestamp.DtmUpd AS [REF_COURSE.DTM_UPD], 
            T.LastUserTimestamp.UsrUpd AS [REF_COURSE.USR_UPD], 
            True AS _from0
        FROM TrainingEntities.RefCourses AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_MAJOR
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_MAJOR", @"
    SELECT VALUE -- Constructing REF_MAJOR
        [TrainingModel.Store.REF_MAJOR](T1.[REF_MAJOR.REF_MAJOR_ID], T1.[REF_MAJOR.MAJOR_CODE], T1.[REF_MAJOR.FACULTY], T1.[REF_MAJOR.MAJOR_NAME], T1.[REF_MAJOR.DTM_CRT], T1.[REF_MAJOR.USR_CRT], T1.[REF_MAJOR.DTM_UPD], T1.[REF_MAJOR.USR_UPD])
    FROM (
        SELECT 
            T.RefMajorId AS [REF_MAJOR.REF_MAJOR_ID], 
            T.MajorCode AS [REF_MAJOR.MAJOR_CODE], 
            T.Faculty AS [REF_MAJOR.FACULTY], 
            T.MajorName AS [REF_MAJOR.MAJOR_NAME], 
            T.LastUserTimestamp.DtmCrt AS [REF_MAJOR.DTM_CRT], 
            T.LastUserTimestamp.UsrCrt AS [REF_MAJOR.USR_CRT], 
            T.LastUserTimestamp.DtmUpd AS [REF_MAJOR.DTM_UPD], 
            T.LastUserTimestamp.UsrUpd AS [REF_MAJOR.USR_UPD], 
            True AS _from0
        FROM TrainingEntities.RefMajors AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.STUDENT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.STUDENT", @"
    SELECT VALUE -- Constructing STUDENT
        [TrainingModel.Store.STUDENT](T1.[STUDENT.STUDENT_ID], T1.STUDENT_NAME, T1.[STUDENT.STUDENT_NO], T1.STUDENT_ADDRESS, T1.[STUDENT.BIRTH_PLACE], T1.[STUDENT.BIRTH_DT], T1.[STUDENT.REF_MAJOR_ID], T1.[STUDENT.DTM_CRT], T1.[STUDENT.USR_CRT], T1.[STUDENT.DTM_UPD], T1.[STUDENT.USR_UPD])
    FROM (
        SELECT 
            T.StudentId AS [STUDENT.STUDENT_ID], 
            T.Name AS STUDENT_NAME, 
            T.StudentNo AS [STUDENT.STUDENT_NO], 
            T.Address AS STUDENT_ADDRESS, 
            T.BirthPlace AS [STUDENT.BIRTH_PLACE], 
            T.BirthDt AS [STUDENT.BIRTH_DT], 
            T.RefMajorId AS [STUDENT.REF_MAJOR_ID], 
            T.LastUserTimestamp.DtmCrt AS [STUDENT.DTM_CRT], 
            T.LastUserTimestamp.UsrCrt AS [STUDENT.USR_CRT], 
            T.LastUserTimestamp.DtmUpd AS [STUDENT.DTM_UPD], 
            T.LastUserTimestamp.UsrUpd AS [STUDENT.USR_UPD], 
            True AS _from0
        FROM TrainingEntities.Students AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.STUDENT_SCORE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.STUDENT_SCORE", @"
    SELECT VALUE -- Constructing STUDENT_SCORE
        [TrainingModel.Store.STUDENT_SCORE](T1.[STUDENT_SCORE.STUDENT_SCORE_ID], T1.[STUDENT_SCORE.STUDENT_ID], T1.[STUDENT_SCORE.REF_COURSE_ID], T1.[STUDENT_SCORE.SCORE], T1.[STUDENT_SCORE.DTM_CRT], T1.[STUDENT_SCORE.USR_CRT], T1.[STUDENT_SCORE.DTM_UPD], T1.[STUDENT_SCORE.USR_UPD])
    FROM (
        SELECT 
            T.StudentScoreId AS [STUDENT_SCORE.STUDENT_SCORE_ID], 
            T.StudentId AS [STUDENT_SCORE.STUDENT_ID], 
            T.RefCourseId AS [STUDENT_SCORE.REF_COURSE_ID], 
            T.Score AS [STUDENT_SCORE.SCORE], 
            T.LastUserTimestamp.DtmCrt AS [STUDENT_SCORE.DTM_CRT], 
            T.LastUserTimestamp.UsrCrt AS [STUDENT_SCORE.USR_CRT], 
            T.LastUserTimestamp.DtmUpd AS [STUDENT_SCORE.DTM_UPD], 
            T.LastUserTimestamp.UsrUpd AS [STUDENT_SCORE.USR_UPD], 
            True AS _from0
        FROM TrainingEntities.StudentScores AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefCourses
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefCourses", @"
    SELECT VALUE -- Constructing RefCourses
        [TrainingModel.RefCourse](T2.RefCourse_RefCourseId, T2.RefCourse_CourseCode, T2.RefCourse_CourseName, T2.RefCourse_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefCourse_RefCourseId, 
            T1.RefCourse_CourseCode, 
            T1.RefCourse_CourseName, 
            [TrainingModel.UserTimestamp](T1.RefCourse_LastUserTimestamp_UsrCrt, T1.RefCourse_LastUserTimestamp_DtmCrt, T1.RefCourse_LastUserTimestamp_UsrUpd, T1.RefCourse_LastUserTimestamp_DtmUpd) AS RefCourse_LastUserTimestamp
        FROM (
            SELECT 
                T.REF_COURSE_ID AS RefCourse_RefCourseId, 
                T.COURSE_CODE AS RefCourse_CourseCode, 
                T.COURSE_NAME AS RefCourse_CourseName, 
                T.USR_CRT AS RefCourse_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS RefCourse_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS RefCourse_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS RefCourse_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.REF_COURSE AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefMajors
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefMajors", @"
    SELECT VALUE -- Constructing RefMajors
        [TrainingModel.RefMajor](T2.RefMajor_RefMajorId, T2.RefMajor_MajorCode, T2.RefMajor_Faculty, T2.RefMajor_MajorName, T2.RefMajor_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefMajor_RefMajorId, 
            T1.RefMajor_MajorCode, 
            T1.RefMajor_Faculty, 
            T1.RefMajor_MajorName, 
            [TrainingModel.UserTimestamp](T1.RefMajor_LastUserTimestamp_UsrCrt, T1.RefMajor_LastUserTimestamp_DtmCrt, T1.RefMajor_LastUserTimestamp_UsrUpd, T1.RefMajor_LastUserTimestamp_DtmUpd) AS RefMajor_LastUserTimestamp
        FROM (
            SELECT 
                T.REF_MAJOR_ID AS RefMajor_RefMajorId, 
                T.MAJOR_CODE AS RefMajor_MajorCode, 
                T.FACULTY AS RefMajor_Faculty, 
                T.MAJOR_NAME AS RefMajor_MajorName, 
                T.USR_CRT AS RefMajor_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS RefMajor_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS RefMajor_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS RefMajor_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.REF_MAJOR AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Students
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Students", "\r\n    SELECT VALUE -- Constructing Students\r\n        [TrainingModel.Student](T2.S" +
                    "tudent_StudentId, T2.Student_Name, T2.Student_StudentNo, T2.Student_Address, T2." +
                    "Student_BirthPlace, T2.Student_BirthDt, T2.Student_RefMajorId, T2.Student_LastUs" +
                    "erTimestamp)\r\n    FROM (\r\n        SELECT -- Constructing LastUserTimestamp\r\n    " +
                    "        T1.Student_StudentId, \r\n            T1.Student_Name, \r\n            T1.St" +
                    "udent_StudentNo, \r\n            T1.Student_Address, \r\n            T1.Student_Birt" +
                    "hPlace, \r\n            T1.Student_BirthDt, \r\n            T1.Student_RefMajorId, \r" +
                    "\n            [TrainingModel.UserTimestamp](T1.Student_LastUserTimestamp_UsrCrt, " +
                    "T1.Student_LastUserTimestamp_DtmCrt, T1.Student_LastUserTimestamp_UsrUpd, T1.Stu" +
                    "dent_LastUserTimestamp_DtmUpd) AS Student_LastUserTimestamp\r\n        FROM (\r\n   " +
                    "         SELECT \r\n                T.STUDENT_ID AS Student_StudentId, \r\n         " +
                    "       T.NAME AS Student_Name, \r\n                T.STUDENT_NO AS Student_Student" +
                    "No, \r\n                T.ADDRESS AS Student_Address, \r\n                T.BIRTH_PL" +
                    "ACE AS Student_BirthPlace, \r\n                T.BIRTH_DT AS Student_BirthDt, \r\n  " +
                    "              T.REF_MAJOR_ID AS Student_RefMajorId, \r\n                T.USR_CRT " +
                    "AS Student_LastUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS Student_Last" +
                    "UserTimestamp_DtmCrt, \r\n                T.USR_UPD AS Student_LastUserTimestamp_U" +
                    "srUpd, \r\n                T.DTM_UPD AS Student_LastUserTimestamp_DtmUpd, \r\n      " +
                    "          True AS _from0\r\n            FROM TrainingModelStoreContainer.STUDENT A" +
                    "S T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.StudentScores
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.StudentScores", @"
    SELECT VALUE -- Constructing StudentScores
        [TrainingModel.StudentScore](T2.StudentScore_StudentScoreId, T2.StudentScore_StudentId, T2.StudentScore_RefCourseId, T2.StudentScore_Score, T2.StudentScore_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.StudentScore_StudentScoreId, 
            T1.StudentScore_StudentId, 
            T1.StudentScore_RefCourseId, 
            T1.StudentScore_Score, 
            [TrainingModel.UserTimestamp](T1.StudentScore_LastUserTimestamp_UsrCrt, T1.StudentScore_LastUserTimestamp_DtmCrt, T1.StudentScore_LastUserTimestamp_UsrUpd, T1.StudentScore_LastUserTimestamp_DtmUpd) AS StudentScore_LastUserTimestamp
        FROM (
            SELECT 
                T.STUDENT_SCORE_ID AS StudentScore_StudentScoreId, 
                T.STUDENT_ID AS StudentScore_StudentId, 
                T.REF_COURSE_ID AS StudentScore_RefCourseId, 
                T.SCORE AS StudentScore_Score, 
                T.USR_CRT AS StudentScore_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS StudentScore_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS StudentScore_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS StudentScore_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.STUDENT_SCORE AS T
        ) AS T1
    ) AS T2");
        }
    }
}
