//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets478CC27D703FFD715BE5FF286B772FC91752C59E91D0A2BD14442ACE2DC5DAE0))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets478CC27D703FFD715BE5FF286B772FC91752C59E91D0A2BD14442ACE2DC5DAE0 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets478CC27D703FFD715BE5FF286B772FC91752C59E91D0A2BD14442ACE2DC5DAE0()
        {
            this.EdmEntityContainerName = "TrainingEntities";
            this.StoreEntityContainerName = "TrainingModelStoreContainer";
            this.HashOverMappingClosure = "82848d8ce2c2b647a25bddd7b6e281b90e87f9d95dbce7be2708ddbe4d4571bb";
            this.HashOverAllExtentViews = "bbe1df15445e6e0d0ca01f8b1d0f08fd0f50c43027e48969ed7e9b6d19ea521e";
            this.ViewCount = 46;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            if ((index == 26))
            {
                return GetView26();
            }
            if ((index == 27))
            {
                return GetView27();
            }
            if ((index == 28))
            {
                return GetView28();
            }
            if ((index == 29))
            {
                return GetView29();
            }
            if ((index == 30))
            {
                return GetView30();
            }
            if ((index == 31))
            {
                return GetView31();
            }
            if ((index == 32))
            {
                return GetView32();
            }
            if ((index == 33))
            {
                return GetView33();
            }
            if ((index == 34))
            {
                return GetView34();
            }
            if ((index == 35))
            {
                return GetView35();
            }
            if ((index == 36))
            {
                return GetView36();
            }
            if ((index == 37))
            {
                return GetView37();
            }
            if ((index == 38))
            {
                return GetView38();
            }
            if ((index == 39))
            {
                return GetView39();
            }
            if ((index == 40))
            {
                return GetView40();
            }
            if ((index == 41))
            {
                return GetView41();
            }
            if ((index == 42))
            {
                return GetView42();
            }
            if ((index == 43))
            {
                return GetView43();
            }
            if ((index == 44))
            {
                return GetView44();
            }
            if ((index == 45))
            {
                return GetView45();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.CUST
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.CUST", @"
    SELECT VALUE -- Constructing CUST
        [TrainingModel.Store.CUST](T1.[CUST.CUST_ID], T1.[CUST.CUST_NO], T1.[CUST.CUST_NAME], T1.[CUST.CUST_TYPE], T1.CUST_ADDRESS, T1.CUST_RT, T1.CUST_RW, T1.CUST_KELURAHAN, T1.CUST_KECAMATAN, T1.CUST_CITY, T1.CUST_ZIPCODE, T1.[CUST.USR_CRT], T1.[CUST.DTM_CRT], T1.[CUST.USR_UPD], T1.[CUST.DTM_UPD])
    FROM (
        SELECT 
            T.CustId AS [CUST.CUST_ID], 
            T.CustNo AS [CUST.CUST_NO], 
            T.CustName AS [CUST.CUST_NAME], 
            T.CustType AS [CUST.CUST_TYPE], 
            T.Address AS CUST_ADDRESS, 
            T.Rt AS CUST_RT, 
            T.Rw AS CUST_RW, 
            T.Kelurahan AS CUST_KELURAHAN, 
            T.Kecamatan AS CUST_KECAMATAN, 
            T.City AS CUST_CITY, 
            T.Zipcode AS CUST_ZIPCODE, 
            T.LastUserTimestamp.UsrCrt AS [CUST.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [CUST.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [CUST.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [CUST.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Custs1 AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PROD_TRX_D
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PROD_TRX_D", @"
    SELECT VALUE -- Constructing PROD_TRX_D
        [TrainingModel.Store.PROD_TRX_D](T1.[PROD_TRX_D.PROD_TRX_D_ID], T1.[PROD_TRX_D.PROD_TRX_H_ID], T1.[PROD_TRX_D.PRODUCT_D_ID], T1.[PROD_TRX_D.QTY], T1.[PROD_TRX_D.USR_CRT], T1.[PROD_TRX_D.DTM_CRT], T1.[PROD_TRX_D.USR_UPD], T1.[PROD_TRX_D.DTM_UPD])
    FROM (
        SELECT 
            T.ProdTrxDId AS [PROD_TRX_D.PROD_TRX_D_ID], 
            T.ProdTrxHId AS [PROD_TRX_D.PROD_TRX_H_ID], 
            T.ProductDId AS [PROD_TRX_D.PRODUCT_D_ID], 
            T.Qty AS [PROD_TRX_D.QTY], 
            T.LastUserTimestamp.UsrCrt AS [PROD_TRX_D.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PROD_TRX_D.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PROD_TRX_D.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PROD_TRX_D.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.ProdTrxDs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PROD_TRX_H
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PROD_TRX_H", @"
    SELECT VALUE -- Constructing PROD_TRX_H
        [TrainingModel.Store.PROD_TRX_H](T1.[PROD_TRX_H.PROD_TRX_H_ID], T1.[PROD_TRX_H.PROD_TRX_NO], T1.[PROD_TRX_H.PROD_TRX_DT], T1.[PROD_TRX_H.CUST_ID], T1.[PROD_TRX_H.TOTAL_PRICE], T1.[PROD_TRX_H.USR_CRT], T1.[PROD_TRX_H.DTM_CRT], T1.[PROD_TRX_H.USR_UPD], T1.[PROD_TRX_H.DTM_UPD])
    FROM (
        SELECT 
            T.ProdTrxHId AS [PROD_TRX_H.PROD_TRX_H_ID], 
            T.ProdTrxNo AS [PROD_TRX_H.PROD_TRX_NO], 
            T.ProdTrxDt AS [PROD_TRX_H.PROD_TRX_DT], 
            T.CustId AS [PROD_TRX_H.CUST_ID], 
            T.TotalPrice AS [PROD_TRX_H.TOTAL_PRICE], 
            T.LastUserTimestamp.UsrCrt AS [PROD_TRX_H.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PROD_TRX_H.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PROD_TRX_H.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PROD_TRX_H.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.ProdTrxHs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PRODUCT_D
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PRODUCT_D", @"
    SELECT VALUE -- Constructing PRODUCT_D
        [TrainingModel.Store.PRODUCT_D](T1.[PRODUCT_D.PRODUCT_D_ID], T1.[PRODUCT_D.PRODUCT_H_ID], T1.[PRODUCT_D.MODEL_CODE], T1.[PRODUCT_D.MODEL_NAME], T1.[PRODUCT_D.PRICE], T1.[PRODUCT_D.USR_CRT], T1.[PRODUCT_D.DTM_CRT], T1.[PRODUCT_D.USR_UPD], T1.[PRODUCT_D.DTM_UPD], T1.[PRODUCT_D.RELEASE_DT])
    FROM (
        SELECT 
            T.ProductDId AS [PRODUCT_D.PRODUCT_D_ID], 
            T.ProductHId AS [PRODUCT_D.PRODUCT_H_ID], 
            T.ModelCode AS [PRODUCT_D.MODEL_CODE], 
            T.ModelName AS [PRODUCT_D.MODEL_NAME], 
            T.Price AS [PRODUCT_D.PRICE], 
            T.LastUserTimestamp.UsrCrt AS [PRODUCT_D.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PRODUCT_D.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PRODUCT_D.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PRODUCT_D.DTM_UPD], 
            T.ReleaseDt AS [PRODUCT_D.RELEASE_DT], 
            True AS _from0
        FROM TrainingEntities.ProductDs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PRODUCT_H
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PRODUCT_H", @"
    SELECT VALUE -- Constructing PRODUCT_H
        [TrainingModel.Store.PRODUCT_H](T1.[PRODUCT_H.PRODUCT_H_ID], T1.[PRODUCT_H.BRAND_CODE], T1.[PRODUCT_H.BRAND_NAME], T1.[PRODUCT_H.USR_CRT], T1.[PRODUCT_H.DTM_CRT], T1.[PRODUCT_H.USR_UPD], T1.[PRODUCT_H.DTM_UPD])
    FROM (
        SELECT 
            T.ProductHId AS [PRODUCT_H.PRODUCT_H_ID], 
            T.BrandCode AS [PRODUCT_H.BRAND_CODE], 
            T.BrandName AS [PRODUCT_H.BRAND_NAME], 
            T.LastUserTimestamp.UsrCrt AS [PRODUCT_H.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PRODUCT_H.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PRODUCT_H.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PRODUCT_H.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.ProductHs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Custs1
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Custs1", "\r\n    SELECT VALUE -- Constructing Custs1\r\n        [TrainingModel.Cust](T2.Cust_C" +
                    "ustId, T2.Cust_CustNo, T2.Cust_CustName, T2.Cust_CustType, T2.Cust_Address, T2.C" +
                    "ust_Rt, T2.Cust_Rw, T2.Cust_Kelurahan, T2.Cust_Kecamatan, T2.Cust_City, T2.Cust_" +
                    "Zipcode, T2.Cust_LastUserTimestamp)\r\n    FROM (\r\n        SELECT -- Constructing " +
                    "LastUserTimestamp\r\n            T1.Cust_CustId, \r\n            T1.Cust_CustNo, \r\n " +
                    "           T1.Cust_CustName, \r\n            T1.Cust_CustType, \r\n            T1.Cu" +
                    "st_Address, \r\n            T1.Cust_Rt, \r\n            T1.Cust_Rw, \r\n            T1" +
                    ".Cust_Kelurahan, \r\n            T1.Cust_Kecamatan, \r\n            T1.Cust_City, \r\n" +
                    "            T1.Cust_Zipcode, \r\n            [TrainingModel.UserTimestamp](T1.Cust" +
                    "_LastUserTimestamp_UsrCrt, T1.Cust_LastUserTimestamp_DtmCrt, T1.Cust_LastUserTim" +
                    "estamp_UsrUpd, T1.Cust_LastUserTimestamp_DtmUpd) AS Cust_LastUserTimestamp\r\n    " +
                    "    FROM (\r\n            SELECT \r\n                T.CUST_ID AS Cust_CustId, \r\n   " +
                    "             T.CUST_NO AS Cust_CustNo, \r\n                T.CUST_NAME AS Cust_Cus" +
                    "tName, \r\n                T.CUST_TYPE AS Cust_CustType, \r\n                T.ADDRE" +
                    "SS AS Cust_Address, \r\n                T.RT AS Cust_Rt, \r\n                T.RW AS" +
                    " Cust_Rw, \r\n                T.KELURAHAN AS Cust_Kelurahan, \r\n                T.K" +
                    "ECAMATAN AS Cust_Kecamatan, \r\n                T.CITY AS Cust_City, \r\n           " +
                    "     T.ZIPCODE AS Cust_Zipcode, \r\n                T.USR_CRT AS Cust_LastUserTime" +
                    "stamp_UsrCrt, \r\n                T.DTM_CRT AS Cust_LastUserTimestamp_DtmCrt, \r\n  " +
                    "              T.USR_UPD AS Cust_LastUserTimestamp_UsrUpd, \r\n                T.DT" +
                    "M_UPD AS Cust_LastUserTimestamp_DtmUpd, \r\n                True AS _from0\r\n      " +
                    "      FROM TrainingModelStoreContainer.CUST AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProdTrxDs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProdTrxDs", @"
    SELECT VALUE -- Constructing ProdTrxDs
        [TrainingModel.ProdTrxD](T2.ProdTrxD_ProdTrxDId, T2.ProdTrxD_ProdTrxHId, T2.ProdTrxD_ProductDId, T2.ProdTrxD_Qty, T2.ProdTrxD_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProdTrxD_ProdTrxDId, 
            T1.ProdTrxD_ProdTrxHId, 
            T1.ProdTrxD_ProductDId, 
            T1.ProdTrxD_Qty, 
            [TrainingModel.UserTimestamp](T1.ProdTrxD_LastUserTimestamp_UsrCrt, T1.ProdTrxD_LastUserTimestamp_DtmCrt, T1.ProdTrxD_LastUserTimestamp_UsrUpd, T1.ProdTrxD_LastUserTimestamp_DtmUpd) AS ProdTrxD_LastUserTimestamp
        FROM (
            SELECT 
                T.PROD_TRX_D_ID AS ProdTrxD_ProdTrxDId, 
                T.PROD_TRX_H_ID AS ProdTrxD_ProdTrxHId, 
                T.PRODUCT_D_ID AS ProdTrxD_ProductDId, 
                T.QTY AS ProdTrxD_Qty, 
                T.USR_CRT AS ProdTrxD_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProdTrxD_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProdTrxD_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProdTrxD_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PROD_TRX_D AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProdTrxHs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProdTrxHs", @"
    SELECT VALUE -- Constructing ProdTrxHs
        [TrainingModel.ProdTrxH](T2.ProdTrxH_ProdTrxHId, T2.ProdTrxH_ProdTrxNo, T2.ProdTrxH_ProdTrxDt, T2.ProdTrxH_CustId, T2.ProdTrxH_TotalPrice, T2.ProdTrxH_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProdTrxH_ProdTrxHId, 
            T1.ProdTrxH_ProdTrxNo, 
            T1.ProdTrxH_ProdTrxDt, 
            T1.ProdTrxH_CustId, 
            T1.ProdTrxH_TotalPrice, 
            [TrainingModel.UserTimestamp](T1.ProdTrxH_LastUserTimestamp_UsrCrt, T1.ProdTrxH_LastUserTimestamp_DtmCrt, T1.ProdTrxH_LastUserTimestamp_UsrUpd, T1.ProdTrxH_LastUserTimestamp_DtmUpd) AS ProdTrxH_LastUserTimestamp
        FROM (
            SELECT 
                T.PROD_TRX_H_ID AS ProdTrxH_ProdTrxHId, 
                T.PROD_TRX_NO AS ProdTrxH_ProdTrxNo, 
                T.PROD_TRX_DT AS ProdTrxH_ProdTrxDt, 
                T.CUST_ID AS ProdTrxH_CustId, 
                T.TOTAL_PRICE AS ProdTrxH_TotalPrice, 
                T.USR_CRT AS ProdTrxH_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProdTrxH_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProdTrxH_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProdTrxH_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PROD_TRX_H AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProductDs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProductDs", @"
    SELECT VALUE -- Constructing ProductDs
        [TrainingModel.ProductD](T2.ProductD_ProductDId, T2.ProductD_ProductHId, T2.ProductD_ModelCode, T2.ProductD_ModelName, T2.ProductD_Price, T2.ProductD_ReleaseDt, T2.ProductD_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProductD_ProductDId, 
            T1.ProductD_ProductHId, 
            T1.ProductD_ModelCode, 
            T1.ProductD_ModelName, 
            T1.ProductD_Price, 
            T1.ProductD_ReleaseDt, 
            [TrainingModel.UserTimestamp](T1.ProductD_LastUserTimestamp_UsrCrt, T1.ProductD_LastUserTimestamp_DtmCrt, T1.ProductD_LastUserTimestamp_UsrUpd, T1.ProductD_LastUserTimestamp_DtmUpd) AS ProductD_LastUserTimestamp
        FROM (
            SELECT 
                T.PRODUCT_D_ID AS ProductD_ProductDId, 
                T.PRODUCT_H_ID AS ProductD_ProductHId, 
                T.MODEL_CODE AS ProductD_ModelCode, 
                T.MODEL_NAME AS ProductD_ModelName, 
                T.PRICE AS ProductD_Price, 
                T.RELEASE_DT AS ProductD_ReleaseDt, 
                T.USR_CRT AS ProductD_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProductD_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProductD_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProductD_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PRODUCT_D AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.ProductHs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.ProductHs", @"
    SELECT VALUE -- Constructing ProductHs
        [TrainingModel.ProductH](T2.ProductH_ProductHId, T2.ProductH_BrandCode, T2.ProductH_BrandName, T2.ProductH_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.ProductH_ProductHId, 
            T1.ProductH_BrandCode, 
            T1.ProductH_BrandName, 
            [TrainingModel.UserTimestamp](T1.ProductH_LastUserTimestamp_UsrCrt, T1.ProductH_LastUserTimestamp_DtmCrt, T1.ProductH_LastUserTimestamp_UsrUpd, T1.ProductH_LastUserTimestamp_DtmUpd) AS ProductH_LastUserTimestamp
        FROM (
            SELECT 
                T.PRODUCT_H_ID AS ProductH_ProductHId, 
                T.BRAND_CODE AS ProductH_BrandCode, 
                T.BRAND_NAME AS ProductH_BrandName, 
                T.USR_CRT AS ProductH_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS ProductH_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS ProductH_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS ProductH_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PRODUCT_H AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PRODUCT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PRODUCT", @"
    SELECT VALUE -- Constructing PRODUCT
        [TrainingModel.Store.PRODUCT](T1.[PRODUCT.PRODUCT_ID], T1.[PRODUCT.PRODUCT_CODE], T1.[PRODUCT.PRODUCT_NAME], T1.PRODUCT_PRICE, T1.[PRODUCT.USR_CRT], T1.[PRODUCT.DTM_CRT], T1.[PRODUCT.USR_UPD], T1.[PRODUCT.DTM_UPD], T1.PRODUCT_CONDITION, T1.[PRODUCT.RELEASE_DT])
    FROM (
        SELECT 
            T.ProductId AS [PRODUCT.PRODUCT_ID], 
            T.ProductCode AS [PRODUCT.PRODUCT_CODE], 
            T.ProductName AS [PRODUCT.PRODUCT_NAME], 
            T.Price AS PRODUCT_PRICE, 
            T.LastUserTimestamp.UsrCrt AS [PRODUCT.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PRODUCT.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PRODUCT.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PRODUCT.DTM_UPD], 
            T.Condition AS PRODUCT_CONDITION, 
            T.ReleaseDt AS [PRODUCT.RELEASE_DT], 
            True AS _from0
        FROM TrainingEntities.Products1 AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Products1
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Products1", @"
    SELECT VALUE -- Constructing Products1
        [TrainingModel.Product](T2.Product_ProductId, T2.Product_ProductCode, T2.Product_ProductName, T2.Product_Price, T2.Product_LastUserTimestamp, T2.Product_Condition, T2.Product_ReleaseDt)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Product_ProductId, 
            T1.Product_ProductCode, 
            T1.Product_ProductName, 
            T1.Product_Price, 
            [TrainingModel.UserTimestamp](T1.Product_LastUserTimestamp_UsrCrt, T1.Product_LastUserTimestamp_DtmCrt, T1.Product_LastUserTimestamp_UsrUpd, T1.Product_LastUserTimestamp_DtmUpd) AS Product_LastUserTimestamp, 
            T1.Product_Condition, 
            T1.Product_ReleaseDt
        FROM (
            SELECT 
                T.PRODUCT_ID AS Product_ProductId, 
                T.PRODUCT_CODE AS Product_ProductCode, 
                T.PRODUCT_NAME AS Product_ProductName, 
                T.PRICE AS Product_Price, 
                T.USR_CRT AS Product_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS Product_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS Product_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS Product_LastUserTimestamp_DtmUpd, 
                T.CONDITION AS Product_Condition, 
                T.RELEASE_DT AS Product_ReleaseDt, 
                True AS _from0
            FROM TrainingModelStoreContainer.PRODUCT AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_MASTER
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_MASTER", @"
    SELECT VALUE -- Constructing REF_MASTER
        [TrainingModel.Store.REF_MASTER](T1.[REF_MASTER.REF_MASTER_ID], T1.[REF_MASTER.MASTER_CODE], T1.[REF_MASTER.DESCRIPTION], T1.[REF_MASTER.MASTER_TYPE], T1.[REF_MASTER.USR_CRT], T1.[REF_MASTER.DTM_CRT], T1.[REF_MASTER.USR_UPD], T1.[REF_MASTER.DTM_UPD])
    FROM (
        SELECT 
            T.RefMasterId AS [REF_MASTER.REF_MASTER_ID], 
            T.MasterCode AS [REF_MASTER.MASTER_CODE], 
            T.Description AS [REF_MASTER.DESCRIPTION], 
            T.MasterType AS [REF_MASTER.MASTER_TYPE], 
            T.LastUserTimestamp.UsrCrt AS [REF_MASTER.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [REF_MASTER.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [REF_MASTER.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [REF_MASTER.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.RefMasters AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefMasters
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefMasters", @"
    SELECT VALUE -- Constructing RefMasters
        [TrainingModel.RefMaster](T2.RefMaster_RefMasterId, T2.RefMaster_MasterCode, T2.RefMaster_Description, T2.RefMaster_MasterType, T2.RefMaster_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefMaster_RefMasterId, 
            T1.RefMaster_MasterCode, 
            T1.RefMaster_Description, 
            T1.RefMaster_MasterType, 
            [TrainingModel.UserTimestamp](T1.RefMaster_LastUserTimestamp_UsrCrt, T1.RefMaster_LastUserTimestamp_DtmCrt, T1.RefMaster_LastUserTimestamp_UsrUpd, T1.RefMaster_LastUserTimestamp_DtmUpd) AS RefMaster_LastUserTimestamp
        FROM (
            SELECT 
                T.REF_MASTER_ID AS RefMaster_RefMasterId, 
                T.MASTER_CODE AS RefMaster_MasterCode, 
                T.DESCRIPTION AS RefMaster_Description, 
                T.MASTER_TYPE AS RefMaster_MasterType, 
                T.USR_CRT AS RefMaster_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS RefMaster_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS RefMaster_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS RefMaster_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.REF_MASTER AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.SUPPL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.SUPPL", @"
    SELECT VALUE -- Constructing SUPPL
        [TrainingModel.Store.SUPPL](T1.[SUPPL.SUPPL_ID], T1.[SUPPL.SUPPL_NO], T1.[SUPPL.SUPPL_NAME], T1.[SUPPL.SUPPL_ADDRESS], T1.[SUPPL.SUPPL_RT], T1.[SUPPL.SUPPL_RW], T1.[SUPPL.SUPPL_KELURAHAN], T1.[SUPPL.SUPPL_KECAMATAN], T1.[SUPPL.SUPPL_CITY], T1.[SUPPL.SUPPL_ZIPCODE], T1.[SUPPL.USR_CRT], T1.[SUPPL.DTM_CRT], T1.[SUPPL.USR_UPD], T1.[SUPPL.DTM_UPD], T1.SUPPL_PRODUCE)
    FROM (
        SELECT 
            T.SupplId AS [SUPPL.SUPPL_ID], 
            T.SupplNo AS [SUPPL.SUPPL_NO], 
            T.SupplName AS [SUPPL.SUPPL_NAME], 
            T.SupplAddress AS [SUPPL.SUPPL_ADDRESS], 
            T.SupplRt AS [SUPPL.SUPPL_RT], 
            T.SupplRw AS [SUPPL.SUPPL_RW], 
            T.SupplKelurahan AS [SUPPL.SUPPL_KELURAHAN], 
            T.SupplKecamatan AS [SUPPL.SUPPL_KECAMATAN], 
            T.SupplCity AS [SUPPL.SUPPL_CITY], 
            T.SupplZipcode AS [SUPPL.SUPPL_ZIPCODE], 
            T.LastUserTimestamp.UsrCrt AS [SUPPL.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [SUPPL.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [SUPPL.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [SUPPL.DTM_UPD], 
            T.Produce AS SUPPL_PRODUCE, 
            True AS _from0
        FROM TrainingEntities.Suppls1 AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Suppls1
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Suppls1", "\r\n    SELECT VALUE -- Constructing Suppls1\r\n        [TrainingModel.Suppl](T2.Supp" +
                    "l_SupplId, T2.Suppl_SupplNo, T2.Suppl_SupplName, T2.Suppl_SupplAddress, T2.Suppl" +
                    "_SupplRt, T2.Suppl_SupplRw, T2.Suppl_SupplKelurahan, T2.Suppl_SupplKecamatan, T2" +
                    ".Suppl_SupplCity, T2.Suppl_SupplZipcode, T2.Suppl_Produce, T2.Suppl_LastUserTime" +
                    "stamp)\r\n    FROM (\r\n        SELECT -- Constructing LastUserTimestamp\r\n          " +
                    "  T1.Suppl_SupplId, \r\n            T1.Suppl_SupplNo, \r\n            T1.Suppl_Suppl" +
                    "Name, \r\n            T1.Suppl_SupplAddress, \r\n            T1.Suppl_SupplRt, \r\n   " +
                    "         T1.Suppl_SupplRw, \r\n            T1.Suppl_SupplKelurahan, \r\n            " +
                    "T1.Suppl_SupplKecamatan, \r\n            T1.Suppl_SupplCity, \r\n            T1.Supp" +
                    "l_SupplZipcode, \r\n            T1.Suppl_Produce, \r\n            [TrainingModel.Use" +
                    "rTimestamp](T1.Suppl_LastUserTimestamp_UsrCrt, T1.Suppl_LastUserTimestamp_DtmCrt" +
                    ", T1.Suppl_LastUserTimestamp_UsrUpd, T1.Suppl_LastUserTimestamp_DtmUpd) AS Suppl" +
                    "_LastUserTimestamp\r\n        FROM (\r\n            SELECT \r\n                T.SUPPL" +
                    "_ID AS Suppl_SupplId, \r\n                T.SUPPL_NO AS Suppl_SupplNo, \r\n         " +
                    "       T.SUPPL_NAME AS Suppl_SupplName, \r\n                T.SUPPL_ADDRESS AS Sup" +
                    "pl_SupplAddress, \r\n                T.SUPPL_RT AS Suppl_SupplRt, \r\n              " +
                    "  T.SUPPL_RW AS Suppl_SupplRw, \r\n                T.SUPPL_KELURAHAN AS Suppl_Supp" +
                    "lKelurahan, \r\n                T.SUPPL_KECAMATAN AS Suppl_SupplKecamatan, \r\n     " +
                    "           T.SUPPL_CITY AS Suppl_SupplCity, \r\n                T.SUPPL_ZIPCODE AS" +
                    " Suppl_SupplZipcode, \r\n                T.PRODUCE AS Suppl_Produce, \r\n           " +
                    "     T.USR_CRT AS Suppl_LastUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS" +
                    " Suppl_LastUserTimestamp_DtmCrt, \r\n                T.USR_UPD AS Suppl_LastUserTi" +
                    "mestamp_UsrUpd, \r\n                T.DTM_UPD AS Suppl_LastUserTimestamp_DtmUpd, \r" +
                    "\n                True AS _from0\r\n            FROM TrainingModelStoreContainer.SU" +
                    "PPL AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.OFFICE_HEAD
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.OFFICE_HEAD", @"
    SELECT VALUE -- Constructing OFFICE_HEAD
        [TrainingModel.Store.OFFICE_HEAD](T1.[OFFICE_HEAD.OFFICE_HEAD_ID], T1.[OFFICE_HEAD.OFFICE_HEAD_NAME], T1.[OFFICE_HEAD.EMAIL], T1.[OFFICE_HEAD.PHN], T1.[OFFICE_HEAD.MOBILE_PHN], T1.[OFFICE_HEAD.USR_UPD], T1.[OFFICE_HEAD.DTM_UPD], T1.[OFFICE_HEAD.USR_CRT], T1.[OFFICE_HEAD.DTM_CRT], T1.[OFFICE_HEAD.REF_OFFICE_ID])
    FROM (
        SELECT 
            T.OfficeHeadId AS [OFFICE_HEAD.OFFICE_HEAD_ID], 
            T.OfficeHeadName AS [OFFICE_HEAD.OFFICE_HEAD_NAME], 
            T.Email AS [OFFICE_HEAD.EMAIL], 
            T.Phn AS [OFFICE_HEAD.PHN], 
            T.MobliePhn AS [OFFICE_HEAD.MOBILE_PHN], 
            T.LastUserTimestamp.UsrUpd AS [OFFICE_HEAD.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [OFFICE_HEAD.DTM_UPD], 
            T.LastUserTimestamp.UsrCrt AS [OFFICE_HEAD.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [OFFICE_HEAD.DTM_CRT], 
            T.RefOifficeId AS [OFFICE_HEAD.REF_OFFICE_ID], 
            True AS _from0
        FROM TrainingEntities.OfficeHeads AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_OFFICE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_OFFICE", @"
    SELECT VALUE -- Constructing REF_OFFICE
        [TrainingModel.Store.REF_OFFICE](T1.[REF_OFFICE.REF_OFFICE_ID], T1.[REF_OFFICE.OFFICE_CODE], T1.[REF_OFFICE.OFFICE_NAME], T1.[REF_OFFICE.ADDR], T1.[REF_OFFICE.RT], T1.[REF_OFFICE.RW], T1.[REF_OFFICE.ZIPCODE], T1.[REF_OFFICE.PHN_AREA], T1.[REF_OFFICE.PHN], T1.[REF_OFFICE.OFFICE_BALANCE_AMT], T1.[REF_OFFICE.USR_UPD], T1.[REF_OFFICE.DTM_UPD], T1.[REF_OFFICE.USR_CRT], T1.[REF_OFFICE.DTM_CRT], T1.[REF_OFFICE.IS_ACTIVE])
    FROM (
        SELECT 
            T.RefOfficeId AS [REF_OFFICE.REF_OFFICE_ID], 
            T.OfficeCode AS [REF_OFFICE.OFFICE_CODE], 
            T.OfficeName AS [REF_OFFICE.OFFICE_NAME], 
            T.Addr AS [REF_OFFICE.ADDR], 
            T.Rt AS [REF_OFFICE.RT], 
            T.Rw AS [REF_OFFICE.RW], 
            T.Zipcode AS [REF_OFFICE.ZIPCODE], 
            T.PhnArea AS [REF_OFFICE.PHN_AREA], 
            T.Phn AS [REF_OFFICE.PHN], 
            T.OfficeBalanceAmt AS [REF_OFFICE.OFFICE_BALANCE_AMT], 
            T.LastUserTimestamp.UsrUpd AS [REF_OFFICE.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [REF_OFFICE.DTM_UPD], 
            T.LastUserTimestamp.UsrCrt AS [REF_OFFICE.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [REF_OFFICE.DTM_CRT], 
            T.IsActive AS [REF_OFFICE.IS_ACTIVE], 
            True AS _from0
        FROM TrainingEntities.RefOffices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.EMPLOYEE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.EMPLOYEE", "\r\n    SELECT VALUE -- Constructing EMPLOYEE\r\n        [TrainingModel.Store.EMPLOYE" +
                    "E](T1.[EMPLOYEE.EMPLOYEE_ID], T1.[EMPLOYEE.EMPLOYEE_NO], T1.[EMPLOYEE.EMPLOYEE_F" +
                    "IRST_NAME], T1.[EMPLOYEE.EMPLOYEE_LAST_NAME], T1.[EMPLOYEE.JOIN_DT], T1.EMPLOYEE" +
                    "_POSITION, T1.EMPLOYEE_ADDR, T1.EMPLOYEE_RT, T1.EMPLOYEE_RW, T1.EMPLOYEE_ZIPCODE" +
                    ", T1.EMPLOYEE_PHN, T1.[EMPLOYEE.MOBILE_PHN], T1.EMPLOYEE_EMAIL, T1.[EMPLOYEE.REF" +
                    "_OFFICE_ID], T1.[EMPLOYEE.USR_UPD], T1.[EMPLOYEE.DTM_UPD], T1.[EMPLOYEE.USR_CRT]" +
                    ", T1.[EMPLOYEE.DTM_CRT], T1.[EMPLOYEE.IS_ACTIVE], T1.[EMPLOYEE.OFFICE_HEAD_ID])\r" +
                    "\n    FROM (\r\n        SELECT \r\n            T.EmployeeId AS [EMPLOYEE.EMPLOYEE_ID]" +
                    ", \r\n            T.EmployeeNo AS [EMPLOYEE.EMPLOYEE_NO], \r\n            T.Employee" +
                    "FirstName AS [EMPLOYEE.EMPLOYEE_FIRST_NAME], \r\n            T.EmployeeLastName AS" +
                    " [EMPLOYEE.EMPLOYEE_LAST_NAME], \r\n            T.JoinDt AS [EMPLOYEE.JOIN_DT], \r\n" +
                    "            T.Position AS EMPLOYEE_POSITION, \r\n            T.Addr AS EMPLOYEE_AD" +
                    "DR, \r\n            T.Rt AS EMPLOYEE_RT, \r\n            T.Rw AS EMPLOYEE_RW, \r\n    " +
                    "        T.Zipcode AS EMPLOYEE_ZIPCODE, \r\n            T.Phn AS EMPLOYEE_PHN, \r\n  " +
                    "          T.MobilePhn AS [EMPLOYEE.MOBILE_PHN], \r\n            T.Email AS EMPLOYE" +
                    "E_EMAIL, \r\n            T.RefOfficeId AS [EMPLOYEE.REF_OFFICE_ID], \r\n            " +
                    "T.LastUserTimestamp.UsrUpd AS [EMPLOYEE.USR_UPD], \r\n            T.LastUserTimest" +
                    "amp.DtmUpd AS [EMPLOYEE.DTM_UPD], \r\n            T.LastUserTimestamp.UsrCrt AS [E" +
                    "MPLOYEE.USR_CRT], \r\n            T.LastUserTimestamp.DtmCrt AS [EMPLOYEE.DTM_CRT]" +
                    ", \r\n            T.IsActive AS [EMPLOYEE.IS_ACTIVE], \r\n            T.OfficeHeadId" +
                    " AS [EMPLOYEE.OFFICE_HEAD_ID], \r\n            True AS _from0\r\n        FROM Traini" +
                    "ngEntities.Employees1 AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.OfficeHeads
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.OfficeHeads", "\r\n    SELECT VALUE -- Constructing OfficeHeads\r\n        [TrainingModel.OfficeHead" +
                    "](T2.OfficeHead_OfficeHeadId, T2.OfficeHead_OfficeHeadName, T2.OfficeHead_Email," +
                    " T2.OfficeHead_Phn, T2.OfficeHead_MobliePhn, T2.OfficeHead_RefOifficeId, T2.Offi" +
                    "ceHead_LastUserTimestamp)\r\n    FROM (\r\n        SELECT -- Constructing LastUserTi" +
                    "mestamp\r\n            T1.OfficeHead_OfficeHeadId, \r\n            T1.OfficeHead_Off" +
                    "iceHeadName, \r\n            T1.OfficeHead_Email, \r\n            T1.OfficeHead_Phn," +
                    " \r\n            T1.OfficeHead_MobliePhn, \r\n            T1.OfficeHead_RefOifficeId" +
                    ", \r\n            [TrainingModel.UserTimestamp](T1.OfficeHead_LastUserTimestamp_Us" +
                    "rCrt, T1.OfficeHead_LastUserTimestamp_DtmCrt, T1.OfficeHead_LastUserTimestamp_Us" +
                    "rUpd, T1.OfficeHead_LastUserTimestamp_DtmUpd) AS OfficeHead_LastUserTimestamp\r\n " +
                    "       FROM (\r\n            SELECT \r\n                T.OFFICE_HEAD_ID AS OfficeHe" +
                    "ad_OfficeHeadId, \r\n                T.OFFICE_HEAD_NAME AS OfficeHead_OfficeHeadNa" +
                    "me, \r\n                T.EMAIL AS OfficeHead_Email, \r\n                T.PHN AS Of" +
                    "ficeHead_Phn, \r\n                T.MOBILE_PHN AS OfficeHead_MobliePhn, \r\n        " +
                    "        T.REF_OFFICE_ID AS OfficeHead_RefOifficeId, \r\n                T.USR_CRT " +
                    "AS OfficeHead_LastUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS OfficeHea" +
                    "d_LastUserTimestamp_DtmCrt, \r\n                T.USR_UPD AS OfficeHead_LastUserTi" +
                    "mestamp_UsrUpd, \r\n                T.DTM_UPD AS OfficeHead_LastUserTimestamp_DtmU" +
                    "pd, \r\n                True AS _from0\r\n            FROM TrainingModelStoreContain" +
                    "er.OFFICE_HEAD AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefOffices
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefOffices", "\r\n    SELECT VALUE -- Constructing RefOffices\r\n        [TrainingModel.RefOffice](" +
                    "T2.RefOffice_RefOfficeId, T2.RefOffice_OfficeCode, T2.RefOffice_OfficeName, T2.R" +
                    "efOffice_Addr, T2.RefOffice_Rt, T2.RefOffice_Rw, T2.RefOffice_Zipcode, T2.RefOff" +
                    "ice_PhnArea, T2.RefOffice_Phn, T2.RefOffice_OfficeBalanceAmt, T2.RefOffice_IsAct" +
                    "ive, T2.RefOffice_LastUserTimestamp)\r\n    FROM (\r\n        SELECT -- Constructing" +
                    " LastUserTimestamp\r\n            T1.RefOffice_RefOfficeId, \r\n            T1.RefOf" +
                    "fice_OfficeCode, \r\n            T1.RefOffice_OfficeName, \r\n            T1.RefOffi" +
                    "ce_Addr, \r\n            T1.RefOffice_Rt, \r\n            T1.RefOffice_Rw, \r\n       " +
                    "     T1.RefOffice_Zipcode, \r\n            T1.RefOffice_PhnArea, \r\n            T1." +
                    "RefOffice_Phn, \r\n            T1.RefOffice_OfficeBalanceAmt, \r\n            T1.Ref" +
                    "Office_IsActive, \r\n            [TrainingModel.UserTimestamp](T1.RefOffice_LastUs" +
                    "erTimestamp_UsrCrt, T1.RefOffice_LastUserTimestamp_DtmCrt, T1.RefOffice_LastUser" +
                    "Timestamp_UsrUpd, T1.RefOffice_LastUserTimestamp_DtmUpd) AS RefOffice_LastUserTi" +
                    "mestamp\r\n        FROM (\r\n            SELECT \r\n                T.REF_OFFICE_ID AS" +
                    " RefOffice_RefOfficeId, \r\n                T.OFFICE_CODE AS RefOffice_OfficeCode," +
                    " \r\n                T.OFFICE_NAME AS RefOffice_OfficeName, \r\n                T.AD" +
                    "DR AS RefOffice_Addr, \r\n                T.RT AS RefOffice_Rt, \r\n                " +
                    "T.RW AS RefOffice_Rw, \r\n                T.ZIPCODE AS RefOffice_Zipcode, \r\n      " +
                    "          T.PHN_AREA AS RefOffice_PhnArea, \r\n                T.PHN AS RefOffice_" +
                    "Phn, \r\n                T.OFFICE_BALANCE_AMT AS RefOffice_OfficeBalanceAmt, \r\n   " +
                    "             T.IS_ACTIVE AS RefOffice_IsActive, \r\n                T.USR_CRT AS R" +
                    "efOffice_LastUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS RefOffice_Last" +
                    "UserTimestamp_DtmCrt, \r\n                T.USR_UPD AS RefOffice_LastUserTimestamp" +
                    "_UsrUpd, \r\n                T.DTM_UPD AS RefOffice_LastUserTimestamp_DtmUpd, \r\n  " +
                    "              True AS _from0\r\n            FROM TrainingModelStoreContainer.REF_O" +
                    "FFICE AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Employees1
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2585);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Employees1\r\n        [TrainingModel.Employee](");
            viewString.Append("T2.Employee_EmployeeId, T2.Employee_EmployeeNo, T2.Employee_EmployeeFirstName, T");
            viewString.Append("2.Employee_EmployeeLastName, T2.Employee_JoinDt, T2.Employee_Position, T2.Employ");
            viewString.Append("ee_Addr, T2.Employee_Rt, T2.Employee_Rw, T2.Employee_Zipcode, T2.Employee_Phn, T");
            viewString.Append("2.Employee_MobilePhn, T2.Employee_Email, T2.Employee_RefOfficeId, T2.Employee_Is");
            viewString.Append("Active, T2.Employee_OfficeHeadId, T2.Employee_LastUserTimestamp)\r\n    FROM (\r\n  ");
            viewString.Append("      SELECT -- Constructing LastUserTimestamp\r\n            T1.Employee_Employee");
            viewString.Append("Id, \r\n            T1.Employee_EmployeeNo, \r\n            T1.Employee_EmployeeFirs");
            viewString.Append("tName, \r\n            T1.Employee_EmployeeLastName, \r\n            T1.Employee_Joi");
            viewString.Append("nDt, \r\n            T1.Employee_Position, \r\n            T1.Employee_Addr, \r\n     ");
            viewString.Append("       T1.Employee_Rt, \r\n            T1.Employee_Rw, \r\n            T1.Employee_Z");
            viewString.Append("ipcode, \r\n            T1.Employee_Phn, \r\n            T1.Employee_MobilePhn, \r\n  ");
            viewString.Append("          T1.Employee_Email, \r\n            T1.Employee_RefOfficeId, \r\n          ");
            viewString.Append("  T1.Employee_IsActive, \r\n            T1.Employee_OfficeHeadId, \r\n            [T");
            viewString.Append("rainingModel.UserTimestamp](T1.Employee_LastUserTimestamp_UsrCrt, T1.Employee_La");
            viewString.Append("stUserTimestamp_DtmCrt, T1.Employee_LastUserTimestamp_UsrUpd, T1.Employee_LastUs");
            viewString.Append("erTimestamp_DtmUpd) AS Employee_LastUserTimestamp\r\n        FROM (\r\n            S");
            viewString.Append("ELECT \r\n                T.EMPLOYEE_ID AS Employee_EmployeeId, \r\n                ");
            viewString.Append("T.EMPLOYEE_NO AS Employee_EmployeeNo, \r\n                T.EMPLOYEE_FIRST_NAME AS");
            viewString.Append(" Employee_EmployeeFirstName, \r\n                T.EMPLOYEE_LAST_NAME AS Employee_");
            viewString.Append("EmployeeLastName, \r\n                T.JOIN_DT AS Employee_JoinDt, \r\n            ");
            viewString.Append("    T.POSITION AS Employee_Position, \r\n                T.ADDR AS Employee_Addr, ");
            viewString.Append("\r\n                T.RT AS Employee_Rt, \r\n                T.RW AS Employee_Rw, \r\n");
            viewString.Append("                T.ZIPCODE AS Employee_Zipcode, \r\n                T.PHN AS Employ");
            viewString.Append("ee_Phn, \r\n                T.MOBILE_PHN AS Employee_MobilePhn, \r\n                ");
            viewString.Append("T.EMAIL AS Employee_Email, \r\n                T.REF_OFFICE_ID AS Employee_RefOffi");
            viewString.Append("ceId, \r\n                T.IS_ACTIVE AS Employee_IsActive, \r\n                T.OF");
            viewString.Append("FICE_HEAD_ID AS Employee_OfficeHeadId, \r\n                T.USR_CRT AS Employee_L");
            viewString.Append("astUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS Employee_LastUserTimesta");
            viewString.Append("mp_DtmCrt, \r\n                T.USR_UPD AS Employee_LastUserTimestamp_UsrUpd, \r\n ");
            viewString.Append("               T.DTM_UPD AS Employee_LastUserTimestamp_DtmUpd, \r\n               ");
            viewString.Append(" True AS _from0\r\n            FROM TrainingModelStoreContainer.EMPLOYEE AS T\r\n   ");
            viewString.Append("     ) AS T1\r\n    ) AS T2");
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Employees1", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Agrmnt
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Agrmnt", @"
    SELECT VALUE -- Constructing Agrmnt
        [TrainingModel.Store.Agrmnt](T1.[Agrmnt.Agrmnt_Id], T1.[Agrmnt.App_Id], T1.[Agrmnt.Agrmnt_No], T1.[Agrmnt.Branch_Id], T1.[Agrmnt.Cust_Id], T1.[Agrmnt.Curr_Id], T1.[Agrmnt.App_Step], T1.[Agrmnt.Contract_Stat], T1.[Agrmnt.Inst_Amt], T1.[Agrmnt.Usr_Crt], T1.[Agrmnt.Dtm_Crt], T1.[Agrmnt.Usr_Upd], T1.[Agrmnt.Dtm_Upd])
    FROM (
        SELECT 
            T.AgrmntId AS [Agrmnt.Agrmnt_Id], 
            T.AppId AS [Agrmnt.App_Id], 
            T.AgrmntNo AS [Agrmnt.Agrmnt_No], 
            T.BranchId AS [Agrmnt.Branch_Id], 
            T.CustId AS [Agrmnt.Cust_Id], 
            T.CurrId AS [Agrmnt.Curr_Id], 
            T.AppStep AS [Agrmnt.App_Step], 
            T.ContractStat AS [Agrmnt.Contract_Stat], 
            T.InstAmt AS [Agrmnt.Inst_Amt], 
            T.LastUserTimestamp.UsrCrt AS [Agrmnt.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Agrmnt.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Agrmnt.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Agrmnt.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.Agrmnts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Branch
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Branch", @"
    SELECT VALUE -- Constructing Branch
        [TrainingModel.Store.Branch](T1.[Branch.Branch_Id], T1.[Branch.Branch_Code], T1.[Branch.Branch_Name], T1.[Branch.Usr_Crt], T1.[Branch.Dtm_Crt], T1.[Branch.Usr_Upd], T1.[Branch.Dtm_Upd])
    FROM (
        SELECT 
            T.BranchId AS [Branch.Branch_Id], 
            T.BranchCode AS [Branch.Branch_Code], 
            T.BranchName AS [Branch.Branch_Name], 
            T.LastUserTimestamp.UsrCrt AS [Branch.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Branch.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Branch.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Branch.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.Branches AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Branch_Employee
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Branch_Employee", @"
    SELECT VALUE -- Constructing Branch_Employee
        [TrainingModel.Store.Branch_Employee](T1.[Branch_Employee.Employee_Id], T1.[Branch_Employee.Employee_Name], T1.[Branch_Employee.Position], T1.[Branch_Employee.Usr_Crt], T1.[Branch_Employee.Dtm_Crt], T1.[Branch_Employee.Usr_Upd], T1.[Branch_Employee.Dtm_Upd])
    FROM (
        SELECT 
            T.EmployeeId AS [Branch_Employee.Employee_Id], 
            T.EmployeeName AS [Branch_Employee.Employee_Name], 
            T.Position AS [Branch_Employee.Position], 
            T.LastUserTimestamp.UsrCrt AS [Branch_Employee.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Branch_Employee.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Branch_Employee.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Branch_Employee.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.BranchEmployees AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Curr
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Curr", @"
    SELECT VALUE -- Constructing Curr
        [TrainingModel.Store.Curr](T1.[Curr.Curr_Id], T1.[Curr.Curr_Code], T1.[Curr.Curr_Name], T1.[Curr.Usr_Crt], T1.[Curr.Dtm_Crt], T1.[Curr.Usr_Upd], T1.[Curr.Dtm_Upd])
    FROM (
        SELECT 
            T.CurrId AS [Curr.Curr_Id], 
            T.CurrCode AS [Curr.Curr_Code], 
            T.CurrName AS [Curr.Curr_Name], 
            T.LastUserTimestamp.UsrCrt AS [Curr.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Curr.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Curr.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Curr.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.Currs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_Detail
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView26()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_Detail", @"
    SELECT VALUE -- Constructing PDC_Detail
        [TrainingModel.Store.PDC_Detail](T1.[PDC_Detail.PDC_Detail_Id], T1.[PDC_Detail.PDC_Header_Id], T1.[PDC_Detail.Payment_Allocation], T1.[PDC_Detail.Description], T1.[PDC_Detail.Amount], T1.[PDC_Detail.Usr_Crt], T1.[PDC_Detail.Dtm_Crt], T1.[PDC_Detail.Usr_Upd], T1.[PDC_Detail.Dtm_Upd])
    FROM (
        SELECT 
            T.PDCDetailId AS [PDC_Detail.PDC_Detail_Id], 
            T.PDCHeaderId AS [PDC_Detail.PDC_Header_Id], 
            T.PaymentAllocation AS [PDC_Detail.Payment_Allocation], 
            T.Description AS [PDC_Detail.Description], 
            T.Amount AS [PDC_Detail.Amount], 
            T.LastUserTimestamp.UsrCrt AS [PDC_Detail.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [PDC_Detail.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [PDC_Detail.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [PDC_Detail.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.PDCDetails AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_Header
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView27()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_Header", "\r\n    SELECT VALUE -- Constructing PDC_Header\r\n        [TrainingModel.Store.PDC_H" +
                    "eader](T1.[PDC_Header.PDC_Header_Id], T1.[PDC_Header.PDC_Receipt_Id], T1.[PDC_He" +
                    "ader.PDC_No], T1.[PDC_Header.Ref_Bank_Id], T1.[PDC_Header.Giro_Seq_No], T1.[PDC_" +
                    "Header.Atas_Nama_PDC], T1.[PDC_Header.Receive_Date], T1.[PDC_Header.Employee_Id]" +
                    ", T1.[PDC_Header.Receive_From], T1.[PDC_Header.PDC_Amount], T1.[PDC_Header.PDC_D" +
                    "ue_Date], T1.[PDC_Header.PDC_Type], T1.[PDC_Header.Is_In_Kaso], T1.[PDC_Header.I" +
                    "s_Cummulative_Flag], T1.[PDC_Header.PDC_Status], T1.[PDC_Header.Fisik_Status], T" +
                    "1.[PDC_Header.Status_Date], T1.[PDC_Header.Usr_Crt], T1.[PDC_Header.Dtm_Crt], T1" +
                    ".[PDC_Header.Usr_Upd], T1.[PDC_Header.Dtm_Upd])\r\n    FROM (\r\n        SELECT \r\n  " +
                    "          T.PDCHeaderId AS [PDC_Header.PDC_Header_Id], \r\n            T.PDCReceip" +
                    "tId AS [PDC_Header.PDC_Receipt_Id], \r\n            T.PDCNo AS [PDC_Header.PDC_No]" +
                    ", \r\n            T.RefBankId AS [PDC_Header.Ref_Bank_Id], \r\n            T.GiroSeq" +
                    "No AS [PDC_Header.Giro_Seq_No], \r\n            T.AtasNamaPDC AS [PDC_Header.Atas_" +
                    "Nama_PDC], \r\n            T.ReceiveDate AS [PDC_Header.Receive_Date], \r\n         " +
                    "   T.EmployeeId AS [PDC_Header.Employee_Id], \r\n            T.ReceiveFrom AS [PDC" +
                    "_Header.Receive_From], \r\n            T.PDCAmount AS [PDC_Header.PDC_Amount], \r\n " +
                    "           T.PDCDueDate AS [PDC_Header.PDC_Due_Date], \r\n            T.PDCType AS" +
                    " [PDC_Header.PDC_Type], \r\n            T.IsInKaso AS [PDC_Header.Is_In_Kaso], \r\n " +
                    "           T.IsCummulativeFlag AS [PDC_Header.Is_Cummulative_Flag], \r\n          " +
                    "  T.PDCStatus AS [PDC_Header.PDC_Status], \r\n            T.FisikStatus AS [PDC_He" +
                    "ader.Fisik_Status], \r\n            T.StatusDate AS [PDC_Header.Status_Date], \r\n  " +
                    "          T.LastUserTimestamp.UsrCrt AS [PDC_Header.Usr_Crt], \r\n            T.La" +
                    "stUserTimestamp.DtmCrt AS [PDC_Header.Dtm_Crt], \r\n            T.LastUserTimestam" +
                    "p.UsrUpd AS [PDC_Header.Usr_Upd], \r\n            T.LastUserTimestamp.DtmUpd AS [P" +
                    "DC_Header.Dtm_Upd], \r\n            True AS _from0\r\n        FROM TrainingEntities." +
                    "PDCHeaders AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_History
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView28()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_History", @"
    SELECT VALUE -- Constructing PDC_History
        [TrainingModel.Store.PDC_History](T1.[PDC_History.PDC_History_Id], T1.[PDC_History.PDC_Header_Id], T1.[PDC_History.PDC_Status], T1.[PDC_History.Fisik_Status], T1.[PDC_History.Status_Date], T1.[PDC_History.Usr_Crt], T1.[PDC_History.Dtm_Crt], T1.[PDC_History.Usr_Upd], T1.[PDC_History.Dtm_Upd])
    FROM (
        SELECT 
            T.PDCHistoryId AS [PDC_History.PDC_History_Id], 
            T.PDCHeaderId AS [PDC_History.PDC_Header_Id], 
            T.PDCStatus AS [PDC_History.PDC_Status], 
            T.FisikStatus AS [PDC_History.Fisik_Status], 
            T.StatusDate AS [PDC_History.Status_Date], 
            T.LastUserTimestamp.UsrCrt AS [PDC_History.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [PDC_History.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [PDC_History.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [PDC_History.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.PDCHistories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_Receipt
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView29()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_Receipt", @"
    SELECT VALUE -- Constructing PDC_Receipt
        [TrainingModel.Store.PDC_Receipt](T1.[PDC_Receipt.PDC_Receipt_Id], T1.[PDC_Receipt.PDC_Receipt_No], T1.[PDC_Receipt.Received_Date], T1.[PDC_Receipt.Receive_From], T1.[PDC_Receipt.Agrmnt_Id], T1.[PDC_Receipt.Num_Of_PDC], T1.[PDC_Receipt.Total_PDC_Amount], T1.[PDC_Receipt.Usr_Crt], T1.[PDC_Receipt.Dtm_Crt], T1.[PDC_Receipt.Usr_Upd], T1.[PDC_Receipt.Dtm_Upd])
    FROM (
        SELECT 
            T.PDCReceiptId AS [PDC_Receipt.PDC_Receipt_Id], 
            T.PDCReceiptNo AS [PDC_Receipt.PDC_Receipt_No], 
            T.ReceivedDate AS [PDC_Receipt.Received_Date], 
            T.ReceiveFrom AS [PDC_Receipt.Receive_From], 
            T.AgrmntId AS [PDC_Receipt.Agrmnt_Id], 
            T.NumOfPDC AS [PDC_Receipt.Num_Of_PDC], 
            T.TotalPDCAmount AS [PDC_Receipt.Total_PDC_Amount], 
            T.LastUserTimestamp.UsrCrt AS [PDC_Receipt.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [PDC_Receipt.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [PDC_Receipt.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [PDC_Receipt.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.PDCReceipts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Ref_Bank
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView30()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Ref_Bank", @"
    SELECT VALUE -- Constructing Ref_Bank
        [TrainingModel.Store.Ref_Bank](T1.[Ref_Bank.Ref_Bank_Id], T1.[Ref_Bank.Bank_Name], T1.[Ref_Bank.Is_Active], T1.[Ref_Bank.Usr_Crt], T1.[Ref_Bank.Dtm_Crt], T1.[Ref_Bank.Usr_Upd], T1.[Ref_Bank.Dtm_Upd])
    FROM (
        SELECT 
            T.RefBankId AS [Ref_Bank.Ref_Bank_Id], 
            T.BankName AS [Ref_Bank.Bank_Name], 
            T.IsActive AS [Ref_Bank.Is_Active], 
            T.LastUserTimestamp.UsrCrt AS [Ref_Bank.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Ref_Bank.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Ref_Bank.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Ref_Bank.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.RefBanks AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Customer
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView31()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Customer", @"
    SELECT VALUE -- Constructing Customer
        [TrainingModel.Store.Customer](T1.[Customer.Cust_Id], T1.[Customer.Cust_Name], T1.Customer_Address, T1.Customer_Rt, T1.Customer_Rw, T1.Customer_Kelurahan, T1.Customer_Kecamatan, T1.Customer_City, T1.[Customer.Zip_Code], T1.Customer_Phone, T1.[Customer.Usr_Crt], T1.[Customer.Dtm_Crt], T1.[Customer.Usr_Upd], T1.[Customer.Dtm_Upd])
    FROM (
        SELECT 
            T.CustId AS [Customer.Cust_Id], 
            T.CustName AS [Customer.Cust_Name], 
            T.Address AS Customer_Address, 
            T.Rt AS Customer_Rt, 
            T.Rw AS Customer_Rw, 
            T.Kelurahan AS Customer_Kelurahan, 
            T.Kecamatan AS Customer_Kecamatan, 
            T.City AS Customer_City, 
            T.ZipCode AS [Customer.Zip_Code], 
            T.Phone AS Customer_Phone, 
            T.LastUserTimestamp.UsrCrt AS [Customer.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Customer.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Customer.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Customer.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.Customers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Agrmnts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView32()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Agrmnts", "\r\n    SELECT VALUE -- Constructing Agrmnts\r\n        [TrainingModel.Agrmnt](T2.Agr" +
                    "mnt_AgrmntId, T2.Agrmnt_AgrmntNo, T2.Agrmnt_BranchId, T2.Agrmnt_CustId, T2.Agrmn" +
                    "t_CurrId, T2.Agrmnt_AppStep, T2.Agrmnt_ContractStat, T2.Agrmnt_InstAmt, T2.Agrmn" +
                    "t_LastUserTimestamp, T2.Agrmnt_AppId)\r\n    FROM (\r\n        SELECT -- Constructin" +
                    "g LastUserTimestamp\r\n            T1.Agrmnt_AgrmntId, \r\n            T1.Agrmnt_Agr" +
                    "mntNo, \r\n            T1.Agrmnt_BranchId, \r\n            T1.Agrmnt_CustId, \r\n     " +
                    "       T1.Agrmnt_CurrId, \r\n            T1.Agrmnt_AppStep, \r\n            T1.Agrmn" +
                    "t_ContractStat, \r\n            T1.Agrmnt_InstAmt, \r\n            [TrainingModel.Us" +
                    "erTimestamp](T1.Agrmnt_LastUserTimestamp_UsrCrt, T1.Agrmnt_LastUserTimestamp_Dtm" +
                    "Crt, T1.Agrmnt_LastUserTimestamp_UsrUpd, T1.Agrmnt_LastUserTimestamp_DtmUpd) AS " +
                    "Agrmnt_LastUserTimestamp, \r\n            T1.Agrmnt_AppId\r\n        FROM (\r\n       " +
                    "     SELECT \r\n                T.Agrmnt_Id AS Agrmnt_AgrmntId, \r\n                " +
                    "T.Agrmnt_No AS Agrmnt_AgrmntNo, \r\n                T.Branch_Id AS Agrmnt_BranchId" +
                    ", \r\n                T.Cust_Id AS Agrmnt_CustId, \r\n                T.Curr_Id AS A" +
                    "grmnt_CurrId, \r\n                T.App_Step AS Agrmnt_AppStep, \r\n                " +
                    "T.Contract_Stat AS Agrmnt_ContractStat, \r\n                T.Inst_Amt AS Agrmnt_I" +
                    "nstAmt, \r\n                T.Usr_Crt AS Agrmnt_LastUserTimestamp_UsrCrt, \r\n      " +
                    "          T.Dtm_Crt AS Agrmnt_LastUserTimestamp_DtmCrt, \r\n                T.Usr_" +
                    "Upd AS Agrmnt_LastUserTimestamp_UsrUpd, \r\n                T.Dtm_Upd AS Agrmnt_La" +
                    "stUserTimestamp_DtmUpd, \r\n                T.App_Id AS Agrmnt_AppId, \r\n          " +
                    "      True AS _from0\r\n            FROM TrainingModelStoreContainer.Agrmnt AS T\r\n" +
                    "        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Branches
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView33()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Branches", @"
    SELECT VALUE -- Constructing Branches
        [TrainingModel.Branch](T2.Branch_BranchId, T2.Branch_BranchCode, T2.Branch_BranchName, T2.Branch_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Branch_BranchId, 
            T1.Branch_BranchCode, 
            T1.Branch_BranchName, 
            [TrainingModel.UserTimestamp](T1.Branch_LastUserTimestamp_UsrCrt, T1.Branch_LastUserTimestamp_DtmCrt, T1.Branch_LastUserTimestamp_UsrUpd, T1.Branch_LastUserTimestamp_DtmUpd) AS Branch_LastUserTimestamp
        FROM (
            SELECT 
                T.Branch_Id AS Branch_BranchId, 
                T.Branch_Code AS Branch_BranchCode, 
                T.Branch_Name AS Branch_BranchName, 
                T.Usr_Crt AS Branch_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS Branch_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS Branch_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS Branch_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.Branch AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.BranchEmployees
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView34()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.BranchEmployees", @"
    SELECT VALUE -- Constructing BranchEmployees
        [TrainingModel.BranchEmployee](T2.BranchEmployee_EmployeeId, T2.BranchEmployee_EmployeeName, T2.BranchEmployee_Position, T2.BranchEmployee_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.BranchEmployee_EmployeeId, 
            T1.BranchEmployee_EmployeeName, 
            T1.BranchEmployee_Position, 
            [TrainingModel.UserTimestamp](T1.BranchEmployee_LastUserTimestamp_UsrCrt, T1.BranchEmployee_LastUserTimestamp_DtmCrt, T1.BranchEmployee_LastUserTimestamp_UsrUpd, T1.BranchEmployee_LastUserTimestamp_DtmUpd) AS BranchEmployee_LastUserTimestamp
        FROM (
            SELECT 
                T.Employee_Id AS BranchEmployee_EmployeeId, 
                T.Employee_Name AS BranchEmployee_EmployeeName, 
                T.Position AS BranchEmployee_Position, 
                T.Usr_Crt AS BranchEmployee_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS BranchEmployee_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS BranchEmployee_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS BranchEmployee_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.Branch_Employee AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Currs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView35()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Currs", @"
    SELECT VALUE -- Constructing Currs
        [TrainingModel.Curr](T2.Curr_CurrId, T2.Curr_CurrCode, T2.Curr_CurrName, T2.Curr_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Curr_CurrId, 
            T1.Curr_CurrCode, 
            T1.Curr_CurrName, 
            [TrainingModel.UserTimestamp](T1.Curr_LastUserTimestamp_UsrCrt, T1.Curr_LastUserTimestamp_DtmCrt, T1.Curr_LastUserTimestamp_UsrUpd, T1.Curr_LastUserTimestamp_DtmUpd) AS Curr_LastUserTimestamp
        FROM (
            SELECT 
                T.Curr_Id AS Curr_CurrId, 
                T.Curr_Code AS Curr_CurrCode, 
                T.Curr_Name AS Curr_CurrName, 
                T.Usr_Crt AS Curr_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS Curr_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS Curr_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS Curr_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.Curr AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PDCDetails
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView36()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PDCDetails", @"
    SELECT VALUE -- Constructing PDCDetails
        [TrainingModel.PDCDetail](T2.PDCDetail_PDCDetailId, T2.PDCDetail_PDCHeaderId, T2.PDCDetail_PaymentAllocation, T2.PDCDetail_Description, T2.PDCDetail_Amount, T2.PDCDetail_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.PDCDetail_PDCDetailId, 
            T1.PDCDetail_PDCHeaderId, 
            T1.PDCDetail_PaymentAllocation, 
            T1.PDCDetail_Description, 
            T1.PDCDetail_Amount, 
            [TrainingModel.UserTimestamp](T1.PDCDetail_LastUserTimestamp_UsrCrt, T1.PDCDetail_LastUserTimestamp_DtmCrt, T1.PDCDetail_LastUserTimestamp_UsrUpd, T1.PDCDetail_LastUserTimestamp_DtmUpd) AS PDCDetail_LastUserTimestamp
        FROM (
            SELECT 
                T.PDC_Detail_Id AS PDCDetail_PDCDetailId, 
                T.PDC_Header_Id AS PDCDetail_PDCHeaderId, 
                T.Payment_Allocation AS PDCDetail_PaymentAllocation, 
                T.Description AS PDCDetail_Description, 
                T.Amount AS PDCDetail_Amount, 
                T.Usr_Crt AS PDCDetail_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS PDCDetail_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS PDCDetail_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS PDCDetail_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PDC_Detail AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PDCHeaders
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView37()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2898);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PDCHeaders\r\n        [TrainingModel.PDCHeader]");
            viewString.Append("(T2.PDCHeader_PDCHeaderId, T2.PDCHeader_PDCReceiptId, T2.PDCHeader_PDCNo, T2.PDC");
            viewString.Append("Header_RefBankId, T2.PDCHeader_GiroSeqNo, T2.PDCHeader_AtasNamaPDC, T2.PDCHeader");
            viewString.Append("_ReceiveDate, T2.PDCHeader_EmployeeId, T2.PDCHeader_ReceiveFrom, T2.PDCHeader_PD");
            viewString.Append("CAmount, T2.PDCHeader_PDCDueDate, T2.PDCHeader_PDCType, T2.PDCHeader_IsInKaso, T");
            viewString.Append("2.PDCHeader_IsCummulativeFlag, T2.PDCHeader_PDCStatus, T2.PDCHeader_FisikStatus,");
            viewString.Append(" T2.PDCHeader_StatusDate, T2.PDCHeader_LastUserTimestamp)\r\n    FROM (\r\n        S");
            viewString.Append("ELECT -- Constructing LastUserTimestamp\r\n            T1.PDCHeader_PDCHeaderId, \r");
            viewString.Append("\n            T1.PDCHeader_PDCReceiptId, \r\n            T1.PDCHeader_PDCNo, \r\n    ");
            viewString.Append("        T1.PDCHeader_RefBankId, \r\n            T1.PDCHeader_GiroSeqNo, \r\n        ");
            viewString.Append("    T1.PDCHeader_AtasNamaPDC, \r\n            T1.PDCHeader_ReceiveDate, \r\n        ");
            viewString.Append("    T1.PDCHeader_EmployeeId, \r\n            T1.PDCHeader_ReceiveFrom, \r\n         ");
            viewString.Append("   T1.PDCHeader_PDCAmount, \r\n            T1.PDCHeader_PDCDueDate, \r\n            ");
            viewString.Append("T1.PDCHeader_PDCType, \r\n            T1.PDCHeader_IsInKaso, \r\n            T1.PDCH");
            viewString.Append("eader_IsCummulativeFlag, \r\n            T1.PDCHeader_PDCStatus, \r\n            T1.");
            viewString.Append("PDCHeader_FisikStatus, \r\n            T1.PDCHeader_StatusDate, \r\n            [Tra");
            viewString.Append("iningModel.UserTimestamp](T1.PDCHeader_LastUserTimestamp_UsrCrt, T1.PDCHeader_La");
            viewString.Append("stUserTimestamp_DtmCrt, T1.PDCHeader_LastUserTimestamp_UsrUpd, T1.PDCHeader_Last");
            viewString.Append("UserTimestamp_DtmUpd) AS PDCHeader_LastUserTimestamp\r\n        FROM (\r\n          ");
            viewString.Append("  SELECT \r\n                T.PDC_Header_Id AS PDCHeader_PDCHeaderId, \r\n         ");
            viewString.Append("       T.PDC_Receipt_Id AS PDCHeader_PDCReceiptId, \r\n                T.PDC_No AS");
            viewString.Append(" PDCHeader_PDCNo, \r\n                T.Ref_Bank_Id AS PDCHeader_RefBankId, \r\n    ");
            viewString.Append("            T.Giro_Seq_No AS PDCHeader_GiroSeqNo, \r\n                T.Atas_Nama_");
            viewString.Append("PDC AS PDCHeader_AtasNamaPDC, \r\n                T.Receive_Date AS PDCHeader_Rece");
            viewString.Append("iveDate, \r\n                T.Employee_Id AS PDCHeader_EmployeeId, \r\n            ");
            viewString.Append("    T.Receive_From AS PDCHeader_ReceiveFrom, \r\n                T.PDC_Amount AS P");
            viewString.Append("DCHeader_PDCAmount, \r\n                T.PDC_Due_Date AS PDCHeader_PDCDueDate, \r\n");
            viewString.Append("                T.PDC_Type AS PDCHeader_PDCType, \r\n                T.Is_In_Kaso ");
            viewString.Append("AS PDCHeader_IsInKaso, \r\n                T.Is_Cummulative_Flag AS PDCHeader_IsCu");
            viewString.Append("mmulativeFlag, \r\n                T.PDC_Status AS PDCHeader_PDCStatus, \r\n        ");
            viewString.Append("        T.Fisik_Status AS PDCHeader_FisikStatus, \r\n                T.Status_Date");
            viewString.Append(" AS PDCHeader_StatusDate, \r\n                T.Usr_Crt AS PDCHeader_LastUserTimes");
            viewString.Append("tamp_UsrCrt, \r\n                T.Dtm_Crt AS PDCHeader_LastUserTimestamp_DtmCrt, ");
            viewString.Append("\r\n                T.Usr_Upd AS PDCHeader_LastUserTimestamp_UsrUpd, \r\n           ");
            viewString.Append("     T.Dtm_Upd AS PDCHeader_LastUserTimestamp_DtmUpd, \r\n                True AS ");
            viewString.Append("_from0\r\n            FROM TrainingModelStoreContainer.PDC_Header AS T\r\n        ) ");
            viewString.Append("AS T1\r\n    ) AS T2");
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PDCHeaders", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PDCHistories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView38()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PDCHistories", @"
    SELECT VALUE -- Constructing PDCHistories
        [TrainingModel.PDCHistory](T2.PDCHistory_PDCHistoryId, T2.PDCHistory_PDCHeaderId, T2.PDCHistory_PDCStatus, T2.PDCHistory_FisikStatus, T2.PDCHistory_StatusDate, T2.PDCHistory_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.PDCHistory_PDCHistoryId, 
            T1.PDCHistory_PDCHeaderId, 
            T1.PDCHistory_PDCStatus, 
            T1.PDCHistory_FisikStatus, 
            T1.PDCHistory_StatusDate, 
            [TrainingModel.UserTimestamp](T1.PDCHistory_LastUserTimestamp_UsrCrt, T1.PDCHistory_LastUserTimestamp_DtmCrt, T1.PDCHistory_LastUserTimestamp_UsrUpd, T1.PDCHistory_LastUserTimestamp_DtmUpd) AS PDCHistory_LastUserTimestamp
        FROM (
            SELECT 
                T.PDC_History_Id AS PDCHistory_PDCHistoryId, 
                T.PDC_Header_Id AS PDCHistory_PDCHeaderId, 
                T.PDC_Status AS PDCHistory_PDCStatus, 
                T.Fisik_Status AS PDCHistory_FisikStatus, 
                T.Status_Date AS PDCHistory_StatusDate, 
                T.Usr_Crt AS PDCHistory_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS PDCHistory_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS PDCHistory_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS PDCHistory_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PDC_History AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PDCReceipts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView39()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PDCReceipts", "\r\n    SELECT VALUE -- Constructing PDCReceipts\r\n        [TrainingModel.PDCReceipt" +
                    "](T2.PDCReceipt_PDCReceiptId, T2.PDCReceipt_PDCReceiptNo, T2.PDCReceipt_Received" +
                    "Date, T2.PDCReceipt_ReceiveFrom, T2.PDCReceipt_AgrmntId, T2.PDCReceipt_NumOfPDC," +
                    " T2.PDCReceipt_TotalPDCAmount, T2.PDCReceipt_LastUserTimestamp)\r\n    FROM (\r\n   " +
                    "     SELECT -- Constructing LastUserTimestamp\r\n            T1.PDCReceipt_PDCRece" +
                    "iptId, \r\n            T1.PDCReceipt_PDCReceiptNo, \r\n            T1.PDCReceipt_Rec" +
                    "eivedDate, \r\n            T1.PDCReceipt_ReceiveFrom, \r\n            T1.PDCReceipt_" +
                    "AgrmntId, \r\n            T1.PDCReceipt_NumOfPDC, \r\n            T1.PDCReceipt_Tota" +
                    "lPDCAmount, \r\n            [TrainingModel.UserTimestamp](T1.PDCReceipt_LastUserTi" +
                    "mestamp_UsrCrt, T1.PDCReceipt_LastUserTimestamp_DtmCrt, T1.PDCReceipt_LastUserTi" +
                    "mestamp_UsrUpd, T1.PDCReceipt_LastUserTimestamp_DtmUpd) AS PDCReceipt_LastUserTi" +
                    "mestamp\r\n        FROM (\r\n            SELECT \r\n                T.PDC_Receipt_Id A" +
                    "S PDCReceipt_PDCReceiptId, \r\n                T.PDC_Receipt_No AS PDCReceipt_PDCR" +
                    "eceiptNo, \r\n                T.Received_Date AS PDCReceipt_ReceivedDate, \r\n      " +
                    "          T.Receive_From AS PDCReceipt_ReceiveFrom, \r\n                T.Agrmnt_I" +
                    "d AS PDCReceipt_AgrmntId, \r\n                T.Num_Of_PDC AS PDCReceipt_NumOfPDC," +
                    " \r\n                T.Total_PDC_Amount AS PDCReceipt_TotalPDCAmount, \r\n          " +
                    "      T.Usr_Crt AS PDCReceipt_LastUserTimestamp_UsrCrt, \r\n                T.Dtm_" +
                    "Crt AS PDCReceipt_LastUserTimestamp_DtmCrt, \r\n                T.Usr_Upd AS PDCRe" +
                    "ceipt_LastUserTimestamp_UsrUpd, \r\n                T.Dtm_Upd AS PDCReceipt_LastUs" +
                    "erTimestamp_DtmUpd, \r\n                True AS _from0\r\n            FROM TrainingM" +
                    "odelStoreContainer.PDC_Receipt AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefBanks
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView40()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefBanks", @"
    SELECT VALUE -- Constructing RefBanks
        [TrainingModel.RefBank](T2.RefBank_RefBankId, T2.RefBank_BankName, T2.RefBank_IsActive, T2.RefBank_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefBank_RefBankId, 
            T1.RefBank_BankName, 
            T1.RefBank_IsActive, 
            [TrainingModel.UserTimestamp](T1.RefBank_LastUserTimestamp_UsrCrt, T1.RefBank_LastUserTimestamp_DtmCrt, T1.RefBank_LastUserTimestamp_UsrUpd, T1.RefBank_LastUserTimestamp_DtmUpd) AS RefBank_LastUserTimestamp
        FROM (
            SELECT 
                T.Ref_Bank_Id AS RefBank_RefBankId, 
                T.Bank_Name AS RefBank_BankName, 
                T.Is_Active AS RefBank_IsActive, 
                T.Usr_Crt AS RefBank_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS RefBank_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS RefBank_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS RefBank_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.Ref_Bank AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Customers
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView41()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Customers", "\r\n    SELECT VALUE -- Constructing Customers\r\n        [TrainingModel.Customer](T2" +
                    ".Customer_CustId, T2.Customer_CustName, T2.Customer_Address, T2.Customer_Rt, T2." +
                    "Customer_Rw, T2.Customer_Kelurahan, T2.Customer_Kecamatan, T2.Customer_City, T2." +
                    "Customer_ZipCode, T2.Customer_Phone, T2.Customer_LastUserTimestamp)\r\n    FROM (\r" +
                    "\n        SELECT -- Constructing LastUserTimestamp\r\n            T1.Customer_CustI" +
                    "d, \r\n            T1.Customer_CustName, \r\n            T1.Customer_Address, \r\n    " +
                    "        T1.Customer_Rt, \r\n            T1.Customer_Rw, \r\n            T1.Customer_" +
                    "Kelurahan, \r\n            T1.Customer_Kecamatan, \r\n            T1.Customer_City, " +
                    "\r\n            T1.Customer_ZipCode, \r\n            T1.Customer_Phone, \r\n          " +
                    "  [TrainingModel.UserTimestamp](T1.Customer_LastUserTimestamp_UsrCrt, T1.Custome" +
                    "r_LastUserTimestamp_DtmCrt, T1.Customer_LastUserTimestamp_UsrUpd, T1.Customer_La" +
                    "stUserTimestamp_DtmUpd) AS Customer_LastUserTimestamp\r\n        FROM (\r\n         " +
                    "   SELECT \r\n                T.Cust_Id AS Customer_CustId, \r\n                T.Cu" +
                    "st_Name AS Customer_CustName, \r\n                T.Address AS Customer_Address, \r" +
                    "\n                T.Rt AS Customer_Rt, \r\n                T.Rw AS Customer_Rw, \r\n " +
                    "               T.Kelurahan AS Customer_Kelurahan, \r\n                T.Kecamatan " +
                    "AS Customer_Kecamatan, \r\n                T.City AS Customer_City, \r\n            " +
                    "    T.Zip_Code AS Customer_ZipCode, \r\n                T.Phone AS Customer_Phone," +
                    " \r\n                T.Usr_Crt AS Customer_LastUserTimestamp_UsrCrt, \r\n           " +
                    "     T.Dtm_Crt AS Customer_LastUserTimestamp_DtmCrt, \r\n                T.Usr_Upd" +
                    " AS Customer_LastUserTimestamp_UsrUpd, \r\n                T.Dtm_Upd AS Customer_L" +
                    "astUserTimestamp_DtmUpd, \r\n                True AS _from0\r\n            FROM Trai" +
                    "ningModelStoreContainer.Customer AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Holiday
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView42()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Holiday", @"
    SELECT VALUE -- Constructing Holiday
        [TrainingModel.Store.Holiday](T1.[Holiday.Holiday_Id], T1.[Holiday.Holiday_Date], T1.Holiday_Description, T1.[Holiday.Is_Public_Holiday], T1.[Holiday.Usr_Crt], T1.[Holiday.Dtm_Crt], T1.[Holiday.Usr_Upd], T1.[Holiday.Dtm_Upd])
    FROM (
        SELECT 
            T.HolidayId AS [Holiday.Holiday_Id], 
            T.HolidayDate AS [Holiday.Holiday_Date], 
            T.Description AS Holiday_Description, 
            T.IsPublicHoliday AS [Holiday.Is_Public_Holiday], 
            T.LastUserTimestamp.UsrCrt AS [Holiday.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Holiday.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Holiday.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Holiday.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.Holidays AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Holidays
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView43()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Holidays", @"
    SELECT VALUE -- Constructing Holidays
        [TrainingModel.Holiday](T2.Holiday_HolidayId, T2.Holiday_HolidayDate, T2.Holiday_Description, T2.Holiday_IsPublicHoliday, T2.Holiday_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Holiday_HolidayId, 
            T1.Holiday_HolidayDate, 
            T1.Holiday_Description, 
            T1.Holiday_IsPublicHoliday, 
            [TrainingModel.UserTimestamp](T1.Holiday_LastUserTimestamp_UsrCrt, T1.Holiday_LastUserTimestamp_DtmCrt, T1.Holiday_LastUserTimestamp_UsrUpd, T1.Holiday_LastUserTimestamp_DtmUpd) AS Holiday_LastUserTimestamp
        FROM (
            SELECT 
                T.Holiday_Id AS Holiday_HolidayId, 
                T.Holiday_Date AS Holiday_HolidayDate, 
                T.Description AS Holiday_Description, 
                T.Is_Public_Holiday AS Holiday_IsPublicHoliday, 
                T.Usr_Crt AS Holiday_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS Holiday_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS Holiday_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS Holiday_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.Holiday AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.Master_Sequence
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView44()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.Master_Sequence", @"
    SELECT VALUE -- Constructing Master_Sequence
        [TrainingModel.Store.Master_Sequence](T1.[Master_Sequence.Master_Sequence_Id], T1.[Master_Sequence.Sequence_No], T1.[Master_Sequence.Usr_Crt], T1.[Master_Sequence.Dtm_Crt], T1.[Master_Sequence.Usr_Upd], T1.[Master_Sequence.Dtm_Upd])
    FROM (
        SELECT 
            T.MasterSequenceId AS [Master_Sequence.Master_Sequence_Id], 
            T.SequenceNo AS [Master_Sequence.Sequence_No], 
            T.LastUserTimestamp.UsrCrt AS [Master_Sequence.Usr_Crt], 
            T.LastUserTimestamp.DtmCrt AS [Master_Sequence.Dtm_Crt], 
            T.LastUserTimestamp.UsrUpd AS [Master_Sequence.Usr_Upd], 
            T.LastUserTimestamp.DtmUpd AS [Master_Sequence.Dtm_Upd], 
            True AS _from0
        FROM TrainingEntities.MasterSequences AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.MasterSequences
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView45()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.MasterSequences", @"
    SELECT VALUE -- Constructing MasterSequences
        [TrainingModel.MasterSequence](T2.MasterSequence_MasterSequenceId, T2.MasterSequence_SequenceNo, T2.MasterSequence_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.MasterSequence_MasterSequenceId, 
            T1.MasterSequence_SequenceNo, 
            [TrainingModel.UserTimestamp](T1.MasterSequence_LastUserTimestamp_UsrCrt, T1.MasterSequence_LastUserTimestamp_DtmCrt, T1.MasterSequence_LastUserTimestamp_UsrUpd, T1.MasterSequence_LastUserTimestamp_DtmUpd) AS MasterSequence_LastUserTimestamp
        FROM (
            SELECT 
                T.Master_Sequence_Id AS MasterSequence_MasterSequenceId, 
                T.Sequence_No AS MasterSequence_SequenceNo, 
                T.Usr_Crt AS MasterSequence_LastUserTimestamp_UsrCrt, 
                T.Dtm_Crt AS MasterSequence_LastUserTimestamp_DtmCrt, 
                T.Usr_Upd AS MasterSequence_LastUserTimestamp_UsrUpd, 
                T.Dtm_Upd AS MasterSequence_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.Master_Sequence AS T
        ) AS T1
    ) AS T2");
        }
    }
}
