//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets59C227543A0DD789FE797C1CC5C671472EE043FCFA687F8EE2F8427BF3795007))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets59C227543A0DD789FE797C1CC5C671472EE043FCFA687F8EE2F8427BF3795007 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets59C227543A0DD789FE797C1CC5C671472EE043FCFA687F8EE2F8427BF3795007()
        {
            this.EdmEntityContainerName = "TrainingEntities";
            this.StoreEntityContainerName = "TrainingModelStoreContainer";
            this.HashOverMappingClosure = "0c3429f5bc0236934a6b43e2d8d0517813045481c703d981ca82f52f0fae508b";
            this.HashOverAllExtentViews = "abd12e7ef1433dd68011c9914890511dd497ff74bf68ff2e1f29b9e23e885ba6";
            this.ViewCount = 2;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PRODUCT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PRODUCT", @"
    SELECT VALUE -- Constructing PRODUCT
        [TrainingModel.Store.PRODUCT](T1.[PRODUCT.PRODUCT_ID], T1.[PRODUCT.PRODUCT_CODE], T1.[PRODUCT.PRODUCT_NAME], T1.PRODUCT_PRICE, T1.[PRODUCT.USR_CRT], T1.[PRODUCT.DTM_CRT], T1.[PRODUCT.USR_UPD], T1.[PRODUCT.DTM_UPD])
    FROM (
        SELECT 
            T.ProdId AS [PRODUCT.PRODUCT_ID], 
            T.ProdCode AS [PRODUCT.PRODUCT_CODE], 
            T.ProdName AS [PRODUCT.PRODUCT_NAME], 
            T.Price AS PRODUCT_PRICE, 
            T.LastUserTimestamp.UsrCrt AS [PRODUCT.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PRODUCT.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PRODUCT.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PRODUCT.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Prods AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Prods
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Prods", @"
    SELECT VALUE -- Constructing Prods
        [TrainingModel.Prod](T2.Prod_ProdId, T2.Prod_ProdCode, T2.Prod_ProdName, T2.Prod_Price, T2.Prod_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Prod_ProdId, 
            T1.Prod_ProdCode, 
            T1.Prod_ProdName, 
            T1.Prod_Price, 
            [TrainingModel.UserTimestamp](T1.Prod_LastUserTimestamp_UsrCrt, T1.Prod_LastUserTimestamp_DtmCrt, T1.Prod_LastUserTimestamp_UsrUpd, T1.Prod_LastUserTimestamp_DtmUpd) AS Prod_LastUserTimestamp
        FROM (
            SELECT 
                T.PRODUCT_ID AS Prod_ProdId, 
                T.PRODUCT_CODE AS Prod_ProdCode, 
                T.PRODUCT_NAME AS Prod_ProdName, 
                T.PRICE AS Prod_Price, 
                T.USR_CRT AS Prod_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS Prod_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS Prod_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS Prod_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PRODUCT AS T
        ) AS T1
    ) AS T2");
        }
    }
}
