//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rule.Web.WebUserControl.Lookup {
    
    
    public partial class UCLookupProduce {
        
        /// <summary>
        /// uclLookupProduce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rule.Web.WebUserControl.GenericLookup.LookupBase uclLookupProduce;
    }
}
