//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsE16BFC872C0B45282F919133DAC251F75344AA92F6778B063C13658A55ACE645))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsE16BFC872C0B45282F919133DAC251F75344AA92F6778B063C13658A55ACE645 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySetsE16BFC872C0B45282F919133DAC251F75344AA92F6778B063C13658A55ACE645()
        {
            this.EdmEntityContainerName = "TrainingEntities";
            this.StoreEntityContainerName = "TrainingModelStoreContainer";
            this.HashOverMappingClosure = "2c31f776f82ac4ca179e8d1b4575b5c76a9b78b74ce2da4358de3da4b6711b41";
            this.HashOverAllExtentViews = "8ea4e1291d01f58dd8854a89b11638ebc6023d5f979148755a6876a6b2a4f67d";
            this.ViewCount = 24;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.AGRMNT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.AGRMNT", @"
    SELECT VALUE -- Constructing AGRMNT
        [TrainingModel.Store.AGRMNT](T1.[AGRMNT.AGRMNT_ID], T1.[AGRMNT.APP_NO], T1.[AGRMNT.AGRMNT_NO], T1.[AGRMNT.BRANCH_ID], T1.[AGRMNT.CUSTOMER_ID], T1.[AGRMNT.CURRENCY_ID], T1.[AGRMNT.APP_STEP], T1.[AGRMNT.CONTRACT_STAT], T1.[AGRMNT.INST_AMT], T1.[AGRMNT.USR_CRT], T1.[AGRMNT.DTM_CRT], T1.[AGRMNT.USR_UPD], T1.[AGRMNT.DTM_UPD])
    FROM (
        SELECT 
            T.AgrmntId AS [AGRMNT.AGRMNT_ID], 
            T.AppNo AS [AGRMNT.APP_NO], 
            T.AgrmntNo AS [AGRMNT.AGRMNT_NO], 
            T.BranchId AS [AGRMNT.BRANCH_ID], 
            T.CustomerId AS [AGRMNT.CUSTOMER_ID], 
            T.CurrencyId AS [AGRMNT.CURRENCY_ID], 
            T.AppStep AS [AGRMNT.APP_STEP], 
            T.ContractStat AS [AGRMNT.CONTRACT_STAT], 
            T.InstAmt AS [AGRMNT.INST_AMT], 
            T.LastUserTimestamp.UsrCrt AS [AGRMNT.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [AGRMNT.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [AGRMNT.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [AGRMNT.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Agrmnts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.BRANCH
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.BRANCH", @"
    SELECT VALUE -- Constructing BRANCH
        [TrainingModel.Store.BRANCH](T1.[BRANCH.BRANCH_ID], T1.[BRANCH.BRANCH_CODE], T1.[BRANCH.BRANCH_NAME], T1.[BRANCH.USR_CRT], T1.[BRANCH.DTM_CRT], T1.[BRANCH.USR_UPD], T1.[BRANCH.DTM_UPD])
    FROM (
        SELECT 
            T.BranchId AS [BRANCH.BRANCH_ID], 
            T.BranchCode AS [BRANCH.BRANCH_CODE], 
            T.BranchName AS [BRANCH.BRANCH_NAME], 
            T.LastUserTimestamp.UsrCrt AS [BRANCH.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [BRANCH.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [BRANCH.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [BRANCH.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Branches AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.CUSTOMER
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.CUSTOMER", @"
    SELECT VALUE -- Constructing CUSTOMER
        [TrainingModel.Store.CUSTOMER](T1.[CUSTOMER.CUSTOMER_ID], T1.[CUSTOMER.CUSTOMER_NAME], T1.[CUSTOMER.CUSTOMER_NO], T1.[CUSTOMER.CUSTOMER_TYPE], T1.CUSTOMER_ADDRESS, T1.CUSTOMER_RT, T1.CUSTOMER_RW, T1.CUSTOMER_KELURAHAN, T1.CUSTOMER_KECAMATAN, T1.CUSTOMER_CITY, T1.[CUSTOMER.ZIP_CODE], T1.CUSTOMER_PHONE, T1.[CUSTOMER.USR_CRT], T1.[CUSTOMER.DTM_CRT], T1.[CUSTOMER.USR_UPD], T1.[CUSTOMER.DTM_UPD])
    FROM (
        SELECT 
            T.CustomerId AS [CUSTOMER.CUSTOMER_ID], 
            T.CustomerName AS [CUSTOMER.CUSTOMER_NAME], 
            T.CustomerNo AS [CUSTOMER.CUSTOMER_NO], 
            T.CustomerType AS [CUSTOMER.CUSTOMER_TYPE], 
            T.Address AS CUSTOMER_ADDRESS, 
            T.Rt AS CUSTOMER_RT, 
            T.Rw AS CUSTOMER_RW, 
            T.Kelurahan AS CUSTOMER_KELURAHAN, 
            T.Kecamatan AS CUSTOMER_KECAMATAN, 
            T.City AS CUSTOMER_CITY, 
            T.ZipCode AS [CUSTOMER.ZIP_CODE], 
            T.Phone AS CUSTOMER_PHONE, 
            T.LastUserTimestamp.UsrCrt AS [CUSTOMER.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [CUSTOMER.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [CUSTOMER.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [CUSTOMER.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Customers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.EMPLOYEE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.EMPLOYEE", @"
    SELECT VALUE -- Constructing EMPLOYEE
        [TrainingModel.Store.EMPLOYEE](T1.[EMPLOYEE.EMPLOYEE_ID], T1.[EMPLOYEE.EMPLOYEE_NAME], T1.EMPLOYEE_POSITION, T1.[EMPLOYEE.USR_CRT], T1.[EMPLOYEE.DTM_CRT], T1.[EMPLOYEE.USR_UPD], T1.[EMPLOYEE.DTM_UPD])
    FROM (
        SELECT 
            T.EmployeeId AS [EMPLOYEE.EMPLOYEE_ID], 
            T.EmployeeName AS [EMPLOYEE.EMPLOYEE_NAME], 
            T.Position AS EMPLOYEE_POSITION, 
            T.LastUserTimestamp.UsrCrt AS [EMPLOYEE.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [EMPLOYEE.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [EMPLOYEE.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [EMPLOYEE.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Employees AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_DETAIL
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_DETAIL", @"
    SELECT VALUE -- Constructing PDC_DETAIL
        [TrainingModel.Store.PDC_DETAIL](T1.[PDC_DETAIL.PDC_DETAIL_ID], T1.[PDC_DETAIL.PDC_HEADER_ID], T1.[PDC_DETAIL.PAYMENT_ALLOCATION], T1.[PDC_DETAIL.DESCRIPTION], T1.[PDC_DETAIL.AMOUNT], T1.[PDC_DETAIL.USR_CRT], T1.[PDC_DETAIL.DTM_CRT], T1.[PDC_DETAIL.USR_UPD], T1.[PDC_DETAIL.DTM_UPD])
    FROM (
        SELECT 
            T.PdcDetailId AS [PDC_DETAIL.PDC_DETAIL_ID], 
            T.PdcHeaderId AS [PDC_DETAIL.PDC_HEADER_ID], 
            T.PaymentAllocation AS [PDC_DETAIL.PAYMENT_ALLOCATION], 
            T.Description AS [PDC_DETAIL.DESCRIPTION], 
            T.Amount AS [PDC_DETAIL.AMOUNT], 
            T.LastUserTimestamp.UsrCrt AS [PDC_DETAIL.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PDC_DETAIL.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PDC_DETAIL.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PDC_DETAIL.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.PdcDetails AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_HEADER
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_HEADER", "\r\n    SELECT VALUE -- Constructing PDC_HEADER\r\n        [TrainingModel.Store.PDC_H" +
                    "EADER](T1.[PDC_HEADER.PDC_HEADER_ID], T1.[PDC_HEADER.PDC_RECEIPT_ID], T1.[PDC_HE" +
                    "ADER.AGRMNT_ID], T1.[PDC_HEADER.PDC_NO], T1.[PDC_HEADER.REF_BANK_ID], T1.[PDC_HE" +
                    "ADER.GIRO_SEQ_NO], T1.[PDC_HEADER.RECEIVE_DATE], T1.[PDC_HEADER.PDC_AMOUNT], T1." +
                    "[PDC_HEADER.PDC_DUE_DATE], T1.[PDC_HEADER.PDC_TYPE], T1.[PDC_HEADER.IS_INKASO], " +
                    "T1.[PDC_HEADER.IS_CUMMULATIVE], T1.[PDC_HEADER.PDC_STATUS], T1.[PDC_HEADER.FISIK" +
                    "_STATUS], T1.[PDC_HEADER.USR_CRT], T1.[PDC_HEADER.DTM_CRT], T1.[PDC_HEADER.USR_U" +
                    "PD], T1.[PDC_HEADER.DTM_UPD])\r\n    FROM (\r\n        SELECT \r\n            T.PdcHea" +
                    "derId AS [PDC_HEADER.PDC_HEADER_ID], \r\n            T.PdcReceiptId AS [PDC_HEADER" +
                    ".PDC_RECEIPT_ID], \r\n            T.AgrmntId AS [PDC_HEADER.AGRMNT_ID], \r\n        " +
                    "    T.PdcNo AS [PDC_HEADER.PDC_NO], \r\n            T.RefBankId AS [PDC_HEADER.REF" +
                    "_BANK_ID], \r\n            T.GiroSeqNo AS [PDC_HEADER.GIRO_SEQ_NO], \r\n            " +
                    "T.ReceiveDate AS [PDC_HEADER.RECEIVE_DATE], \r\n            T.PdcAmount AS [PDC_HE" +
                    "ADER.PDC_AMOUNT], \r\n            T.PdcDueDate AS [PDC_HEADER.PDC_DUE_DATE], \r\n   " +
                    "         T.PdcType AS [PDC_HEADER.PDC_TYPE], \r\n            T.IsInkaso AS [PDC_HE" +
                    "ADER.IS_INKASO], \r\n            T.IsCummulative AS [PDC_HEADER.IS_CUMMULATIVE], \r" +
                    "\n            T.PdcStatus AS [PDC_HEADER.PDC_STATUS], \r\n            T.FisikStatus" +
                    " AS [PDC_HEADER.FISIK_STATUS], \r\n            T.LastUserTimestamp.UsrCrt AS [PDC_" +
                    "HEADER.USR_CRT], \r\n            T.LastUserTimestamp.DtmCrt AS [PDC_HEADER.DTM_CRT" +
                    "], \r\n            T.LastUserTimestamp.UsrUpd AS [PDC_HEADER.USR_UPD], \r\n         " +
                    "   T.LastUserTimestamp.DtmUpd AS [PDC_HEADER.DTM_UPD], \r\n            True AS _fr" +
                    "om0\r\n        FROM TrainingEntities.PdcHeaders AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_HISTORY
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_HISTORY", @"
    SELECT VALUE -- Constructing PDC_HISTORY
        [TrainingModel.Store.PDC_HISTORY](T1.[PDC_HISTORY.PDC_HISTORY_ID], T1.[PDC_HISTORY.PDC_HEADER_ID], T1.[PDC_HISTORY.PDC_STATUS], T1.[PDC_HISTORY.FISIK_STATUS], T1.[PDC_HISTORY.STATUS_DATE], T1.[PDC_HISTORY.USR_CRT], T1.[PDC_HISTORY.DTM_CRT], T1.[PDC_HISTORY.USR_UPD], T1.[PDC_HISTORY.DTM_UPD])
    FROM (
        SELECT 
            T.PdcHistoryId AS [PDC_HISTORY.PDC_HISTORY_ID], 
            T.PdcHeaderId AS [PDC_HISTORY.PDC_HEADER_ID], 
            T.PdcStatus AS [PDC_HISTORY.PDC_STATUS], 
            T.FisikStatus AS [PDC_HISTORY.FISIK_STATUS], 
            T.StatusDate AS [PDC_HISTORY.STATUS_DATE], 
            T.LastUserTimestamp.UsrCrt AS [PDC_HISTORY.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PDC_HISTORY.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PDC_HISTORY.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PDC_HISTORY.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.PdcHistories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.PDC_RECEIPT
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.PDC_RECEIPT", @"
    SELECT VALUE -- Constructing PDC_RECEIPT
        [TrainingModel.Store.PDC_RECEIPT](T1.[PDC_RECEIPT.PDC_RECEIPT_ID], T1.[PDC_RECEIPT.PDC_RECEIPT_NO], T1.[PDC_RECEIPT.RECEIVE_DATE], T1.[PDC_RECEIPT.RECEIVE_FROM], T1.[PDC_RECEIPT.EMPLOYEE_ID], T1.[PDC_RECEIPT.ATAS_NAMA_PDC], T1.[PDC_RECEIPT.NUM_OF_PDC], T1.[PDC_RECEIPT.TOTAL_PDC_AMT], T1.[PDC_RECEIPT.USR_CRT], T1.[PDC_RECEIPT.DTM_CRT], T1.[PDC_RECEIPT.USR_UPD], T1.[PDC_RECEIPT.DTM_UPD])
    FROM (
        SELECT 
            T.PdcReceiptId AS [PDC_RECEIPT.PDC_RECEIPT_ID], 
            T.PdcReceiptNo AS [PDC_RECEIPT.PDC_RECEIPT_NO], 
            T.ReceiveDate AS [PDC_RECEIPT.RECEIVE_DATE], 
            T.ReceiveFrom AS [PDC_RECEIPT.RECEIVE_FROM], 
            T.EmployeeId AS [PDC_RECEIPT.EMPLOYEE_ID], 
            T.AtasNamaPdc AS [PDC_RECEIPT.ATAS_NAMA_PDC], 
            T.NumOfPdc AS [PDC_RECEIPT.NUM_OF_PDC], 
            T.TotalPdcAmt AS [PDC_RECEIPT.TOTAL_PDC_AMT], 
            T.LastUserTimestamp.UsrCrt AS [PDC_RECEIPT.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [PDC_RECEIPT.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [PDC_RECEIPT.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [PDC_RECEIPT.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.PdcReceipts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_BANK
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_BANK", @"
    SELECT VALUE -- Constructing REF_BANK
        [TrainingModel.Store.REF_BANK](T1.[REF_BANK.REF_BANK_ID], T1.[REF_BANK.BANK_CODE], T1.[REF_BANK.BANK_NAME], T1.[REF_BANK.IS_ACTIVE], T1.[REF_BANK.USR_CRT], T1.[REF_BANK.DTM_CRT], T1.[REF_BANK.USR_UPD], T1.[REF_BANK.DTM_UPD])
    FROM (
        SELECT 
            T.RefBankId AS [REF_BANK.REF_BANK_ID], 
            T.BankCode AS [REF_BANK.BANK_CODE], 
            T.BankName AS [REF_BANK.BANK_NAME], 
            T.IsActive AS [REF_BANK.IS_ACTIVE], 
            T.LastUserTimestamp.UsrCrt AS [REF_BANK.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [REF_BANK.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [REF_BANK.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [REF_BANK.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.RefBanks AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.REF_CURRENCY
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.REF_CURRENCY", @"
    SELECT VALUE -- Constructing REF_CURRENCY
        [TrainingModel.Store.REF_CURRENCY](T1.[REF_CURRENCY.REF_CURRENCY_ID], T1.[REF_CURRENCY.CURRENCY_CODE], T1.[REF_CURRENCY.CURRENCY_NAME], T1.[REF_CURRENCY.IS_ACTIVE], T1.[REF_CURRENCY.USR_CRT], T1.[REF_CURRENCY.DTM_CRT], T1.[REF_CURRENCY.USR_UPD], T1.[REF_CURRENCY.DTM_UPD])
    FROM (
        SELECT 
            T.RefCurrencyId AS [REF_CURRENCY.REF_CURRENCY_ID], 
            T.CurrencyCode AS [REF_CURRENCY.CURRENCY_CODE], 
            T.CurrencyName AS [REF_CURRENCY.CURRENCY_NAME], 
            T.IsActive AS [REF_CURRENCY.IS_ACTIVE], 
            T.LastUserTimestamp.UsrCrt AS [REF_CURRENCY.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [REF_CURRENCY.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [REF_CURRENCY.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [REF_CURRENCY.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.RefCurrencies AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Agrmnts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Agrmnts", "\r\n    SELECT VALUE -- Constructing Agrmnts\r\n        [TrainingModel.Agrmnt](T2.Agr" +
                    "mnt_AgrmntId, T2.Agrmnt_AppNo, T2.Agrmnt_AgrmntNo, T2.Agrmnt_BranchId, T2.Agrmnt" +
                    "_CustomerId, T2.Agrmnt_CurrencyId, T2.Agrmnt_AppStep, T2.Agrmnt_ContractStat, T2" +
                    ".Agrmnt_InstAmt, T2.Agrmnt_LastUserTimestamp)\r\n    FROM (\r\n        SELECT -- Con" +
                    "structing LastUserTimestamp\r\n            T1.Agrmnt_AgrmntId, \r\n            T1.Ag" +
                    "rmnt_AppNo, \r\n            T1.Agrmnt_AgrmntNo, \r\n            T1.Agrmnt_BranchId, " +
                    "\r\n            T1.Agrmnt_CustomerId, \r\n            T1.Agrmnt_CurrencyId, \r\n      " +
                    "      T1.Agrmnt_AppStep, \r\n            T1.Agrmnt_ContractStat, \r\n            T1." +
                    "Agrmnt_InstAmt, \r\n            [TrainingModel.UserTimestamp](T1.Agrmnt_LastUserTi" +
                    "mestamp_UsrCrt, T1.Agrmnt_LastUserTimestamp_DtmCrt, T1.Agrmnt_LastUserTimestamp_" +
                    "UsrUpd, T1.Agrmnt_LastUserTimestamp_DtmUpd) AS Agrmnt_LastUserTimestamp\r\n       " +
                    " FROM (\r\n            SELECT \r\n                T.AGRMNT_ID AS Agrmnt_AgrmntId, \r\n" +
                    "                T.APP_NO AS Agrmnt_AppNo, \r\n                T.AGRMNT_NO AS Agrmn" +
                    "t_AgrmntNo, \r\n                T.BRANCH_ID AS Agrmnt_BranchId, \r\n                " +
                    "T.CUSTOMER_ID AS Agrmnt_CustomerId, \r\n                T.CURRENCY_ID AS Agrmnt_Cu" +
                    "rrencyId, \r\n                T.APP_STEP AS Agrmnt_AppStep, \r\n                T.CO" +
                    "NTRACT_STAT AS Agrmnt_ContractStat, \r\n                T.INST_AMT AS Agrmnt_InstA" +
                    "mt, \r\n                T.USR_CRT AS Agrmnt_LastUserTimestamp_UsrCrt, \r\n          " +
                    "      T.DTM_CRT AS Agrmnt_LastUserTimestamp_DtmCrt, \r\n                T.USR_UPD " +
                    "AS Agrmnt_LastUserTimestamp_UsrUpd, \r\n                T.DTM_UPD AS Agrmnt_LastUs" +
                    "erTimestamp_DtmUpd, \r\n                True AS _from0\r\n            FROM TrainingM" +
                    "odelStoreContainer.AGRMNT AS T\r\n        ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Branches
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Branches", @"
    SELECT VALUE -- Constructing Branches
        [TrainingModel.Branch](T2.Branch_BranchId, T2.Branch_BranchCode, T2.Branch_BranchName, T2.Branch_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Branch_BranchId, 
            T1.Branch_BranchCode, 
            T1.Branch_BranchName, 
            [TrainingModel.UserTimestamp](T1.Branch_LastUserTimestamp_UsrCrt, T1.Branch_LastUserTimestamp_DtmCrt, T1.Branch_LastUserTimestamp_UsrUpd, T1.Branch_LastUserTimestamp_DtmUpd) AS Branch_LastUserTimestamp
        FROM (
            SELECT 
                T.BRANCH_ID AS Branch_BranchId, 
                T.BRANCH_CODE AS Branch_BranchCode, 
                T.BRANCH_NAME AS Branch_BranchName, 
                T.USR_CRT AS Branch_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS Branch_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS Branch_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS Branch_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.BRANCH AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Customers
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2104);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Customers\r\n        [TrainingModel.Customer](T");
            viewString.Append("2.Customer_CustomerId, T2.Customer_CustomerName, T2.Customer_CustomerNo, T2.Cust");
            viewString.Append("omer_CustomerType, T2.Customer_Address, T2.Customer_Rt, T2.Customer_Rw, T2.Custo");
            viewString.Append("mer_Kelurahan, T2.Customer_Kecamatan, T2.Customer_City, T2.Customer_ZipCode, T2.");
            viewString.Append("Customer_Phone, T2.Customer_LastUserTimestamp)\r\n    FROM (\r\n        SELECT -- Co");
            viewString.Append("nstructing LastUserTimestamp\r\n            T1.Customer_CustomerId, \r\n            ");
            viewString.Append("T1.Customer_CustomerName, \r\n            T1.Customer_CustomerNo, \r\n            T1");
            viewString.Append(".Customer_CustomerType, \r\n            T1.Customer_Address, \r\n            T1.Cust");
            viewString.Append("omer_Rt, \r\n            T1.Customer_Rw, \r\n            T1.Customer_Kelurahan, \r\n  ");
            viewString.Append("          T1.Customer_Kecamatan, \r\n            T1.Customer_City, \r\n            T");
            viewString.Append("1.Customer_ZipCode, \r\n            T1.Customer_Phone, \r\n            [TrainingMode");
            viewString.Append("l.UserTimestamp](T1.Customer_LastUserTimestamp_UsrCrt, T1.Customer_LastUserTimes");
            viewString.Append("tamp_DtmCrt, T1.Customer_LastUserTimestamp_UsrUpd, T1.Customer_LastUserTimestamp");
            viewString.Append("_DtmUpd) AS Customer_LastUserTimestamp\r\n        FROM (\r\n            SELECT \r\n   ");
            viewString.Append("             T.CUSTOMER_ID AS Customer_CustomerId, \r\n                T.CUSTOMER_");
            viewString.Append("NAME AS Customer_CustomerName, \r\n                T.CUSTOMER_NO AS Customer_Custo");
            viewString.Append("merNo, \r\n                T.CUSTOMER_TYPE AS Customer_CustomerType, \r\n           ");
            viewString.Append("     T.ADDRESS AS Customer_Address, \r\n                T.RT AS Customer_Rt, \r\n   ");
            viewString.Append("             T.RW AS Customer_Rw, \r\n                T.KELURAHAN AS Customer_Kelu");
            viewString.Append("rahan, \r\n                T.KECAMATAN AS Customer_Kecamatan, \r\n                T.");
            viewString.Append("CITY AS Customer_City, \r\n                T.ZIP_CODE AS Customer_ZipCode, \r\n     ");
            viewString.Append("           T.PHONE AS Customer_Phone, \r\n                T.USR_CRT AS Customer_La");
            viewString.Append("stUserTimestamp_UsrCrt, \r\n                T.DTM_CRT AS Customer_LastUserTimestam");
            viewString.Append("p_DtmCrt, \r\n                T.USR_UPD AS Customer_LastUserTimestamp_UsrUpd, \r\n  ");
            viewString.Append("              T.DTM_UPD AS Customer_LastUserTimestamp_DtmUpd, \r\n                ");
            viewString.Append("True AS _from0\r\n            FROM TrainingModelStoreContainer.CUSTOMER AS T\r\n    ");
            viewString.Append("    ) AS T1\r\n    ) AS T2");
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Customers", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Employees
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Employees", @"
    SELECT VALUE -- Constructing Employees
        [TrainingModel.Employee](T2.Employee_EmployeeId, T2.Employee_EmployeeName, T2.Employee_Position, T2.Employee_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Employee_EmployeeId, 
            T1.Employee_EmployeeName, 
            T1.Employee_Position, 
            [TrainingModel.UserTimestamp](T1.Employee_LastUserTimestamp_UsrCrt, T1.Employee_LastUserTimestamp_DtmCrt, T1.Employee_LastUserTimestamp_UsrUpd, T1.Employee_LastUserTimestamp_DtmUpd) AS Employee_LastUserTimestamp
        FROM (
            SELECT 
                T.EMPLOYEE_ID AS Employee_EmployeeId, 
                T.EMPLOYEE_NAME AS Employee_EmployeeName, 
                T.POSITION AS Employee_Position, 
                T.USR_CRT AS Employee_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS Employee_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS Employee_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS Employee_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.EMPLOYEE AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PdcDetails
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PdcDetails", @"
    SELECT VALUE -- Constructing PdcDetails
        [TrainingModel.PdcDetail](T2.PdcDetail_PdcDetailId, T2.PdcDetail_PdcHeaderId, T2.PdcDetail_PaymentAllocation, T2.PdcDetail_Description, T2.PdcDetail_Amount, T2.PdcDetail_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.PdcDetail_PdcDetailId, 
            T1.PdcDetail_PdcHeaderId, 
            T1.PdcDetail_PaymentAllocation, 
            T1.PdcDetail_Description, 
            T1.PdcDetail_Amount, 
            [TrainingModel.UserTimestamp](T1.PdcDetail_LastUserTimestamp_UsrCrt, T1.PdcDetail_LastUserTimestamp_DtmCrt, T1.PdcDetail_LastUserTimestamp_UsrUpd, T1.PdcDetail_LastUserTimestamp_DtmUpd) AS PdcDetail_LastUserTimestamp
        FROM (
            SELECT 
                T.PDC_DETAIL_ID AS PdcDetail_PdcDetailId, 
                T.PDC_HEADER_ID AS PdcDetail_PdcHeaderId, 
                T.PAYMENT_ALLOCATION AS PdcDetail_PaymentAllocation, 
                T.DESCRIPTION AS PdcDetail_Description, 
                T.AMOUNT AS PdcDetail_Amount, 
                T.USR_CRT AS PdcDetail_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS PdcDetail_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS PdcDetail_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS PdcDetail_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PDC_DETAIL AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PdcHeaders
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2500);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PdcHeaders\r\n        [TrainingModel.PdcHeader]");
            viewString.Append("(T2.PdcHeader_PdcHeaderId, T2.PdcHeader_PdcReceiptId, T2.PdcHeader_AgrmntId, T2.");
            viewString.Append("PdcHeader_PdcNo, T2.PdcHeader_RefBankId, T2.PdcHeader_GiroSeqNo, T2.PdcHeader_Re");
            viewString.Append("ceiveDate, T2.PdcHeader_PdcAmount, T2.PdcHeader_PdcDueDate, T2.PdcHeader_PdcType");
            viewString.Append(", T2.PdcHeader_IsInkaso, T2.PdcHeader_IsCummulative, T2.PdcHeader_PdcStatus, T2.");
            viewString.Append("PdcHeader_FisikStatus, T2.PdcHeader_LastUserTimestamp)\r\n    FROM (\r\n        SELE");
            viewString.Append("CT -- Constructing LastUserTimestamp\r\n            T1.PdcHeader_PdcHeaderId, \r\n  ");
            viewString.Append("          T1.PdcHeader_PdcReceiptId, \r\n            T1.PdcHeader_AgrmntId, \r\n    ");
            viewString.Append("        T1.PdcHeader_PdcNo, \r\n            T1.PdcHeader_RefBankId, \r\n            ");
            viewString.Append("T1.PdcHeader_GiroSeqNo, \r\n            T1.PdcHeader_ReceiveDate, \r\n            T1");
            viewString.Append(".PdcHeader_PdcAmount, \r\n            T1.PdcHeader_PdcDueDate, \r\n            T1.Pd");
            viewString.Append("cHeader_PdcType, \r\n            T1.PdcHeader_IsInkaso, \r\n            T1.PdcHeader");
            viewString.Append("_IsCummulative, \r\n            T1.PdcHeader_PdcStatus, \r\n            T1.PdcHeader");
            viewString.Append("_FisikStatus, \r\n            [TrainingModel.UserTimestamp](T1.PdcHeader_LastUserT");
            viewString.Append("imestamp_UsrCrt, T1.PdcHeader_LastUserTimestamp_DtmCrt, T1.PdcHeader_LastUserTim");
            viewString.Append("estamp_UsrUpd, T1.PdcHeader_LastUserTimestamp_DtmUpd) AS PdcHeader_LastUserTimes");
            viewString.Append("tamp\r\n        FROM (\r\n            SELECT \r\n                T.PDC_HEADER_ID AS Pd");
            viewString.Append("cHeader_PdcHeaderId, \r\n                T.PDC_RECEIPT_ID AS PdcHeader_PdcReceiptI");
            viewString.Append("d, \r\n                T.AGRMNT_ID AS PdcHeader_AgrmntId, \r\n                T.PDC_");
            viewString.Append("NO AS PdcHeader_PdcNo, \r\n                T.REF_BANK_ID AS PdcHeader_RefBankId, \r");
            viewString.Append("\n                T.GIRO_SEQ_NO AS PdcHeader_GiroSeqNo, \r\n                T.RECEI");
            viewString.Append("VE_DATE AS PdcHeader_ReceiveDate, \r\n                T.PDC_AMOUNT AS PdcHeader_Pd");
            viewString.Append("cAmount, \r\n                T.PDC_DUE_DATE AS PdcHeader_PdcDueDate, \r\n           ");
            viewString.Append("     T.PDC_TYPE AS PdcHeader_PdcType, \r\n                T.IS_INKASO AS PdcHeader");
            viewString.Append("_IsInkaso, \r\n                T.IS_CUMMULATIVE AS PdcHeader_IsCummulative, \r\n    ");
            viewString.Append("            T.PDC_STATUS AS PdcHeader_PdcStatus, \r\n                T.FISIK_STATU");
            viewString.Append("S AS PdcHeader_FisikStatus, \r\n                T.USR_CRT AS PdcHeader_LastUserTim");
            viewString.Append("estamp_UsrCrt, \r\n                T.DTM_CRT AS PdcHeader_LastUserTimestamp_DtmCrt");
            viewString.Append(", \r\n                T.USR_UPD AS PdcHeader_LastUserTimestamp_UsrUpd, \r\n         ");
            viewString.Append("       T.DTM_UPD AS PdcHeader_LastUserTimestamp_DtmUpd, \r\n                True A");
            viewString.Append("S _from0\r\n            FROM TrainingModelStoreContainer.PDC_HEADER AS T\r\n        ");
            viewString.Append(") AS T1\r\n    ) AS T2");
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PdcHeaders", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PdcHistories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PdcHistories", @"
    SELECT VALUE -- Constructing PdcHistories
        [TrainingModel.PdcHistory](T2.PdcHistory_PdcHistoryId, T2.PdcHistory_PdcHeaderId, T2.PdcHistory_PdcStatus, T2.PdcHistory_FisikStatus, T2.PdcHistory_StatusDate, T2.PdcHistory_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.PdcHistory_PdcHistoryId, 
            T1.PdcHistory_PdcHeaderId, 
            T1.PdcHistory_PdcStatus, 
            T1.PdcHistory_FisikStatus, 
            T1.PdcHistory_StatusDate, 
            [TrainingModel.UserTimestamp](T1.PdcHistory_LastUserTimestamp_UsrCrt, T1.PdcHistory_LastUserTimestamp_DtmCrt, T1.PdcHistory_LastUserTimestamp_UsrUpd, T1.PdcHistory_LastUserTimestamp_DtmUpd) AS PdcHistory_LastUserTimestamp
        FROM (
            SELECT 
                T.PDC_HISTORY_ID AS PdcHistory_PdcHistoryId, 
                T.PDC_HEADER_ID AS PdcHistory_PdcHeaderId, 
                T.PDC_STATUS AS PdcHistory_PdcStatus, 
                T.FISIK_STATUS AS PdcHistory_FisikStatus, 
                T.STATUS_DATE AS PdcHistory_StatusDate, 
                T.USR_CRT AS PdcHistory_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS PdcHistory_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS PdcHistory_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS PdcHistory_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.PDC_HISTORY AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.PdcReceipts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.PdcReceipts", "\r\n    SELECT VALUE -- Constructing PdcReceipts\r\n        [TrainingModel.PdcReceipt" +
                    "](T2.PdcReceipt_PdcReceiptId, T2.PdcReceipt_PdcReceiptNo, T2.PdcReceipt_ReceiveD" +
                    "ate, T2.PdcReceipt_ReceiveFrom, T2.PdcReceipt_EmployeeId, T2.PdcReceipt_AtasNama" +
                    "Pdc, T2.PdcReceipt_NumOfPdc, T2.PdcReceipt_TotalPdcAmt, T2.PdcReceipt_LastUserTi" +
                    "mestamp)\r\n    FROM (\r\n        SELECT -- Constructing LastUserTimestamp\r\n        " +
                    "    T1.PdcReceipt_PdcReceiptId, \r\n            T1.PdcReceipt_PdcReceiptNo, \r\n    " +
                    "        T1.PdcReceipt_ReceiveDate, \r\n            T1.PdcReceipt_ReceiveFrom, \r\n  " +
                    "          T1.PdcReceipt_EmployeeId, \r\n            T1.PdcReceipt_AtasNamaPdc, \r\n " +
                    "           T1.PdcReceipt_NumOfPdc, \r\n            T1.PdcReceipt_TotalPdcAmt, \r\n  " +
                    "          [TrainingModel.UserTimestamp](T1.PdcReceipt_LastUserTimestamp_UsrCrt, " +
                    "T1.PdcReceipt_LastUserTimestamp_DtmCrt, T1.PdcReceipt_LastUserTimestamp_UsrUpd, " +
                    "T1.PdcReceipt_LastUserTimestamp_DtmUpd) AS PdcReceipt_LastUserTimestamp\r\n       " +
                    " FROM (\r\n            SELECT \r\n                T.PDC_RECEIPT_ID AS PdcReceipt_Pdc" +
                    "ReceiptId, \r\n                T.PDC_RECEIPT_NO AS PdcReceipt_PdcReceiptNo, \r\n    " +
                    "            T.RECEIVE_DATE AS PdcReceipt_ReceiveDate, \r\n                T.RECEIV" +
                    "E_FROM AS PdcReceipt_ReceiveFrom, \r\n                T.EMPLOYEE_ID AS PdcReceipt_" +
                    "EmployeeId, \r\n                T.ATAS_NAMA_PDC AS PdcReceipt_AtasNamaPdc, \r\n     " +
                    "           T.NUM_OF_PDC AS PdcReceipt_NumOfPdc, \r\n                T.TOTAL_PDC_AM" +
                    "T AS PdcReceipt_TotalPdcAmt, \r\n                T.USR_CRT AS PdcReceipt_LastUserT" +
                    "imestamp_UsrCrt, \r\n                T.DTM_CRT AS PdcReceipt_LastUserTimestamp_Dtm" +
                    "Crt, \r\n                T.USR_UPD AS PdcReceipt_LastUserTimestamp_UsrUpd, \r\n     " +
                    "           T.DTM_UPD AS PdcReceipt_LastUserTimestamp_DtmUpd, \r\n                T" +
                    "rue AS _from0\r\n            FROM TrainingModelStoreContainer.PDC_RECEIPT AS T\r\n  " +
                    "      ) AS T1\r\n    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefBanks
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefBanks", @"
    SELECT VALUE -- Constructing RefBanks
        [TrainingModel.RefBank](T2.RefBank_RefBankId, T2.RefBank_BankCode, T2.RefBank_BankName, T2.RefBank_IsActive, T2.RefBank_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefBank_RefBankId, 
            T1.RefBank_BankCode, 
            T1.RefBank_BankName, 
            T1.RefBank_IsActive, 
            [TrainingModel.UserTimestamp](T1.RefBank_LastUserTimestamp_UsrCrt, T1.RefBank_LastUserTimestamp_DtmCrt, T1.RefBank_LastUserTimestamp_UsrUpd, T1.RefBank_LastUserTimestamp_DtmUpd) AS RefBank_LastUserTimestamp
        FROM (
            SELECT 
                T.REF_BANK_ID AS RefBank_RefBankId, 
                T.BANK_CODE AS RefBank_BankCode, 
                T.BANK_NAME AS RefBank_BankName, 
                T.IS_ACTIVE AS RefBank_IsActive, 
                T.USR_CRT AS RefBank_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS RefBank_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS RefBank_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS RefBank_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.REF_BANK AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.RefCurrencies
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.RefCurrencies", @"
    SELECT VALUE -- Constructing RefCurrencies
        [TrainingModel.RefCurrency](T2.RefCurrency_RefCurrencyId, T2.RefCurrency_CurrencyCode, T2.RefCurrency_CurrencyName, T2.RefCurrency_IsActive, T2.RefCurrency_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.RefCurrency_RefCurrencyId, 
            T1.RefCurrency_CurrencyCode, 
            T1.RefCurrency_CurrencyName, 
            T1.RefCurrency_IsActive, 
            [TrainingModel.UserTimestamp](T1.RefCurrency_LastUserTimestamp_UsrCrt, T1.RefCurrency_LastUserTimestamp_DtmCrt, T1.RefCurrency_LastUserTimestamp_UsrUpd, T1.RefCurrency_LastUserTimestamp_DtmUpd) AS RefCurrency_LastUserTimestamp
        FROM (
            SELECT 
                T.REF_CURRENCY_ID AS RefCurrency_RefCurrencyId, 
                T.CURRENCY_CODE AS RefCurrency_CurrencyCode, 
                T.CURRENCY_NAME AS RefCurrency_CurrencyName, 
                T.IS_ACTIVE AS RefCurrency_IsActive, 
                T.USR_CRT AS RefCurrency_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS RefCurrency_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS RefCurrency_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS RefCurrency_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.REF_CURRENCY AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.HOLIDAY
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.HOLIDAY", @"
    SELECT VALUE -- Constructing HOLIDAY
        [TrainingModel.Store.HOLIDAY](T1.[HOLIDAY.HOLIDAY_ID], T1.[HOLIDAY.HOLIDAY_DATE], T1.HOLIDAY_DESCRIPTION, T1.[HOLIDAY.IS_PUBLIC_HOLIDAY], T1.[HOLIDAY.USR_CRT], T1.[HOLIDAY.DTM_CRT], T1.[HOLIDAY.USR_UPD], T1.[HOLIDAY.DTM_UPD])
    FROM (
        SELECT 
            T.HolidayId AS [HOLIDAY.HOLIDAY_ID], 
            T.HolidayDate AS [HOLIDAY.HOLIDAY_DATE], 
            T.Description AS HOLIDAY_DESCRIPTION, 
            T.IsPublicHoliday AS [HOLIDAY.IS_PUBLIC_HOLIDAY], 
            T.LastUserTimestamp.UsrCrt AS [HOLIDAY.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [HOLIDAY.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [HOLIDAY.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [HOLIDAY.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.Holidays AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.Holidays
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.Holidays", @"
    SELECT VALUE -- Constructing Holidays
        [TrainingModel.Holiday](T2.Holiday_HolidayId, T2.Holiday_HolidayDate, T2.Holiday_Description, T2.Holiday_IsPublicHoliday, T2.Holiday_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.Holiday_HolidayId, 
            T1.Holiday_HolidayDate, 
            T1.Holiday_Description, 
            T1.Holiday_IsPublicHoliday, 
            [TrainingModel.UserTimestamp](T1.Holiday_LastUserTimestamp_UsrCrt, T1.Holiday_LastUserTimestamp_DtmCrt, T1.Holiday_LastUserTimestamp_UsrUpd, T1.Holiday_LastUserTimestamp_DtmUpd) AS Holiday_LastUserTimestamp
        FROM (
            SELECT 
                T.HOLIDAY_ID AS Holiday_HolidayId, 
                T.HOLIDAY_DATE AS Holiday_HolidayDate, 
                T.DESCRIPTION AS Holiday_Description, 
                T.IS_PUBLIC_HOLIDAY AS Holiday_IsPublicHoliday, 
                T.USR_CRT AS Holiday_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS Holiday_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS Holiday_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS Holiday_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.HOLIDAY AS T
        ) AS T1
    ) AS T2");
        }
        
        /// <Summary>
        /// return view for TrainingModelStoreContainer.MASTER_SEQUENCE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingModelStoreContainer.MASTER_SEQUENCE", @"
    SELECT VALUE -- Constructing MASTER_SEQUENCE
        [TrainingModel.Store.MASTER_SEQUENCE](T1.[MASTER_SEQUENCE.MASTER_SEQUENCE_ID], T1.[MASTER_SEQUENCE.SEQ_NO], T1.[MASTER_SEQUENCE.USR_CRT], T1.[MASTER_SEQUENCE.DTM_CRT], T1.[MASTER_SEQUENCE.USR_UPD], T1.[MASTER_SEQUENCE.DTM_UPD])
    FROM (
        SELECT 
            T.MasterSequenceId AS [MASTER_SEQUENCE.MASTER_SEQUENCE_ID], 
            T.SeqNo AS [MASTER_SEQUENCE.SEQ_NO], 
            T.LastUserTimestamp.UsrCrt AS [MASTER_SEQUENCE.USR_CRT], 
            T.LastUserTimestamp.DtmCrt AS [MASTER_SEQUENCE.DTM_CRT], 
            T.LastUserTimestamp.UsrUpd AS [MASTER_SEQUENCE.USR_UPD], 
            T.LastUserTimestamp.DtmUpd AS [MASTER_SEQUENCE.DTM_UPD], 
            True AS _from0
        FROM TrainingEntities.MasterSequences AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for TrainingEntities.MasterSequences
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("TrainingEntities.MasterSequences", @"
    SELECT VALUE -- Constructing MasterSequences
        [TrainingModel.MasterSequence](T2.MasterSequence_MasterSequenceId, T2.MasterSequence_SeqNo, T2.MasterSequence_LastUserTimestamp)
    FROM (
        SELECT -- Constructing LastUserTimestamp
            T1.MasterSequence_MasterSequenceId, 
            T1.MasterSequence_SeqNo, 
            [TrainingModel.UserTimestamp](T1.MasterSequence_LastUserTimestamp_UsrCrt, T1.MasterSequence_LastUserTimestamp_DtmCrt, T1.MasterSequence_LastUserTimestamp_UsrUpd, T1.MasterSequence_LastUserTimestamp_DtmUpd) AS MasterSequence_LastUserTimestamp
        FROM (
            SELECT 
                T.MASTER_SEQUENCE_ID AS MasterSequence_MasterSequenceId, 
                T.SEQ_NO AS MasterSequence_SeqNo, 
                T.USR_CRT AS MasterSequence_LastUserTimestamp_UsrCrt, 
                T.DTM_CRT AS MasterSequence_LastUserTimestamp_DtmCrt, 
                T.USR_UPD AS MasterSequence_LastUserTimestamp_UsrUpd, 
                T.DTM_UPD AS MasterSequence_LastUserTimestamp_DtmUpd, 
                True AS _from0
            FROM TrainingModelStoreContainer.MASTER_SEQUENCE AS T
        ) AS T1
    ) AS T2");
        }
    }
}
